BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Dominio de Riesgo') X XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Nombre') XXXXXXXXXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXFFFFXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Editar') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Eliminar') XXXX
      XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Riesgos Maestros (N1) asociados') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'REF') XXXXX
          XXXX gettext(u'Nombre') XXXXX
          XXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXX gettext(u'Dominio de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Riesgos (N2)') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXX
          XXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XX X XXXXXXXXXXXXXXXX
                    BBB BB BB BBBBBBBBBBBBBB                                              
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBXX
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXX
                      XXXX                                               
                    BBBBBB
                  XXXXXX                                             
                XXXXXX                                             
              XXXXX
            XXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen Riesgos Maestros (N1) asociados a este dominio de riesgo') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Añadir') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB