# Generated by Django 4.1.3 on 2024-10-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import krm.evaluations.validators
import krm.remediation_plans.models.remediation_plan_answer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0004_alter_controltestanswer_description_and_more'),
        ('controls', '0006_alter_control_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('date_begin', models.DateField(verbose_name='Fecha inicio')),
                ('date_end', models.DateField(verbose_name='Fecha fin')),
                ('descriptiom', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('EP', 'En progreso'), ('CO', 'Completado')], default='SI', max_length=2, verbose_name='Estado')),
                ('additional_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios adicionales')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_control', to='controls.control', verbose_name='Control')),
                ('control_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_control_test', to='evaluations.controltest', verbose_name='Test de control')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario supervisor')),
            ],
            options={
                'verbose_name': 'Plan de remediación',
                'verbose_name_plural': 'Planes de remediación',
            },
        ),
        migrations.CreateModel(
            name='RemediationPlanAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('description', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Comentarios del seguijmiento del plan de remediación')),
                ('attachment_1', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.remediation_plans.models.remediation_plan_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto')),
                ('remediation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='remediation_plans.remediationplan', verbose_name='Plan de Remediación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plan_answers', to=settings.AUTH_USER_MODEL, verbose_name='Autor de la respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta a un Plan de Remediación',
                'verbose_name_plural': 'Respuestas a un Plan de Remediación',
                'ordering': ('remediation_plan', 'created'),
            },
        ),
    ]
