# Generated by Django 4.1.3 on 2024-10-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remediationplan',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
