# Generated by Django 4.1.3 on 2024-10-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0002_rename_descriptiom_remediationplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationplan',
            name='status',
            field=models.CharField(choices=[('EP', 'En progreso'), ('CO', 'Completado')], default='EP', max_length=2, verbose_name='Estado'),
        ),
    ]
