# Generated by Django 4.1.3 on 2024-10-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0003_alter_remediationplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationplananswer',
            name='status',
            field=models.CharField(choices=[('EP', 'En progreso'), ('CO', 'Completado')], default='EP', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='remediationplananswer',
            name='description',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Comentarios del seguimiento del plan de remediación'),
        ),
    ]
