# Generated by Django 4.1.3 on 2024-10-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0004_remediationplananswer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationplan',
            name='status',
            field=models.CharField(choices=[('WR', 'En espera de respuesta del Usuario Responsable'), ('WS', 'En espera de respuesta del Usuario Supervisor'), ('FI', 'Finalizado')], default='WR', max_length=2, verbose_name='¿Quien debe responder?'),
        ),
    ]
