# Generated by Django 4.1.3 on 2024-10-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0005_alter_remediationplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationplan',
            name='next_to_reply',
            field=models.CharField(choices=[('WR', 'En espera de respuesta del Usuario Responsable'), ('WS', 'En espera de respuesta del Usuario Supervisor'), ('FI', 'Finalizado')], default='WR', max_length=2, verbose_name='¿Quien debe responder?'),
        ),
        migrations.AlterField(
            model_name='remediationplan',
            name='status',
            field=models.CharField(choices=[('EP', 'En progreso'), ('CO', 'Completado')], default='EP', max_length=2, verbose_name='Estado'),
        ),
    ]
