# Generated by Django 4.1.3 on 2024-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0006_remediationplan_next_to_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationplananswer',
            name='next_to_reply',
            field=models.CharField(choices=[('WR', 'Responsable'), ('WS', 'Supervisor')], default='WR', max_length=2, verbose_name='¿Quien debe responder?'),
        ),
        migrations.AlterField(
            model_name='remediationplan',
            name='next_to_reply',
            field=models.CharField(choices=[('WR', 'Responsable'), ('WS', 'Supervisor'), ('FI', 'Finalizado')], default='WR', max_length=2, verbose_name='¿Quien debe responder?'),
        ),
    ]
