# Generated by Django 4.1.3 on 2024-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_alter_control_scope'),
        ('remediation_plans', '0008_alter_remediationplananswer_next_to_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediationplan',
            name='control',
        ),
        migrations.AddField(
            model_name='remediationplan',
            name='control',
            field=models.ManyToManyField(blank=True, null=True, related_name='rp_control', to='controls.control', verbose_name='Control'),
        ),
    ]
