# Generated by Django 4.1.3 on 2024-11-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companycontrols_company'),
        ('remediation_plans', '0009_remove_remediationplan_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationplan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='companies.company', verbose_name='Compañía'),
        ),
    ]
