# Generated by Django 4.1.3 on 2024-11-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companycontrols_company'),
        ('controls', '0006_alter_control_scope'),
        ('remediation_plans', '0010_remediationplan_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationplan',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='companies.company', verbose_name='Compañía'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remediationplan',
            name='control',
            field=models.ManyToManyField(blank=True, related_name='rp_control', to='controls.control', verbose_name='Controles'),
        ),
    ]
