# Generated by Django 4.1.3 on 2024-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0011_alter_remediationplan_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationplananswer',
            name='description',
            field=models.TextField(default='   ', help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, verbose_name='Comentarios del seguimiento del plan de remediación'),
            preserve_default=False,
        ),
    ]
