# Generated by Django 4.1.3 on 2024-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0012_alter_remediationplananswer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationplan',
            name='description',
            field=models.TextField(default='   ', max_length=10000, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
