# Generated by Django 4.1.3 on 2025-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation_plans', '0013_alter_remediationplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationplan',
            name='next_to_reply',
            field=models.CharField(choices=[('WR', 'Responsable'), ('WS', 'Supervisor'), ('FI', 'Finalizado')], default='WR', max_length=2, verbose_name='¿Quién debe responder?'),
        ),
        migrations.AlterField(
            model_name='remediationplananswer',
            name='next_to_reply',
            field=models.CharField(choices=[('WR', 'Responsable'), ('WS', 'Supervisor'), ('FI', 'Finalizado')], default='WR', max_length=2, verbose_name='¿Quién debe responder?'),
        ),
    ]
