BBBB BBBB
XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXX

		XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
				 gettext(u'Contacto:') 
			XXXXXX
			XXXX XXXXXXXXXXXXX
				XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX

		XXXXX
		XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
		XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXXXX
		XXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXX

		XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
			XXX XXXXXXXXXXXXXXXXXX
				XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Aviso legal') XXXX
			XXXXX
		XXXXX
		XXXXXXXXXXXXXXXX
	XXXXXX
	XXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXX
