XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
    		XXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXX
  		XXXXXX
		XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
		XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXX
			XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBXXXXXX
		XXXXXX
		XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
			XX XXXXXXXX XXXXXXXXXXXXXXXXXX
        BB BBBBB BB BBBBBBBBBBB
				  XXXX XXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XX
        BBBB
          XXXX XXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XX
        BBBBB
			XXXX
		XXXXXX
		XXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXXXX
		XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
			
      XXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXXXXXXXXXXXXX XXXXXXXXXX
	XXXXXX
	XXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXX
