BBBB BBBB
XXXXXXXXXXXXXXX XXXXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
	XXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
	XXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXX
    BBB B BB BBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXX
      BB BBB BBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
      XXXXX
      BBBBB
    BBBBBB
	XXXXX
	XXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXX XXXXXXXX