XXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
	XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX

		BBBBBBB BBBBBBBBBBBBBBBBBBBB

		XXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBB
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
        BBB BBBBBB BB BBBBBBB
          XX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXX BB BBBBBBBBBBBBBBXXXXXXXXXXXBBBBXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBBBBXX
          BB BBBBBBBBBBB
            FFFF
          BBBBB
          XXXX
        BBBBBB
      XXXXXX
    BBBBB
		XXXXXXXXXXXXXXXXXXX
	XXXXXX
	XXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXX