# Generated by Django 4.1 on 2022-11-30 05:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_controls'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationKrmInherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('date_begin', models.DateField(verbose_name='Inicio de Evaluación')),
                ('date_end', models.DateField(verbose_name='Fin de la Evaluación')),
                ('certification_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Año de certificación')),
                ('certification_period', models.CharField(blank=True, max_length=140, null=True, verbose_name='Periodo de certificación')),
                ('status', models.CharField(choices=[('EP', 'En proceso'), ('FI', 'Finalizado')], default='EP', max_length=2, verbose_name='Estado')),
                ('admin_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador que ha supervisado la evaluación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_inherent_krm', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evaluación Inherente KRM',
                'verbose_name_plural': 'Evaluaciones Inherentes KRM',
            },
        ),
        migrations.CreateModel(
            name='EvaluationKrmResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('date_begin', models.DateField(verbose_name='Inicio de Evaluación')),
                ('date_end', models.DateField(verbose_name='Fin de la Evaluación')),
                ('certification_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Año de certificación')),
                ('certification_period', models.CharField(blank=True, max_length=140, null=True, verbose_name='Periodo de certificación')),
                ('status', models.CharField(choices=[('EP', 'En proceso'), ('FI', 'Finalizado')], default='EP', max_length=2, verbose_name='Estado')),
                ('admin_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador que ha supervisado la evaluación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_residual_krm', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evaluación Residual KRM',
                'verbose_name_plural': 'Evaluaciones Residuals KRM',
            },
        ),
        migrations.CreateModel(
            name='RiskTestResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('probability_level_residual_evaluator', models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Optimizado'), (2, 'Aceptable'), (3, 'Inadecuado'), (4, 'No controlado'), (5, 'N/A')], default=0, verbose_name='Nivel de Probabilidad residual indicado por el Evaluador del Dominio de Riesgo')),
                ('description_evaluator', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Evaluador del Dominio de Riesgo asociado')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Evaluador de Dominio de Riesgo'), (2, 'Esperando al Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_residuals', to='evaluations_krm.evaluationkrmresidual', verbose_name='Evaluación de riesgo residual')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_residuals', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_residual', to='risks.riskcompany')),
            ],
            options={
                'verbose_name': 'Test de Riesgo Residual',
                'verbose_name_plural': 'Tests de Riesgo Residual',
            },
        ),
        migrations.CreateModel(
            name='RiskTestInherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('impact_economic_level_expert', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto Económico indicado por el Experto del Dominio de Riesgo')),
                ('impact_continuity_level_expert', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto en Continuidad indicado por el Experto del Dominio de Riesgo')),
                ('impact_branding_level_expert', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto en Imagen indicado por el Experto del Dominio de Riesgo')),
                ('impact_level_expert', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto indicado por el Experto del Dominio de Riesgo')),
                ('probability_level_expert', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Probabilidad indicado por el Experto del Dominio de Riesgo')),
                ('impact_level_administrator', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto indicado por el Administrador del Dominio de Riesgo')),
                ('probability_level_administrator', models.PositiveSmallIntegerField(choices=[(1, 'No significativo'), (2, 'Bajo'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Probabilidad indicado por el Administrador del Dominio de Riesgo')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Experto de Dominio de Riesgo'), (2, 'Esperando al Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado')),
                ('description', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Experto del Dominio de Riesgo asociado')),
                ('description_admin', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Administrador de la Compañía Evaluada')),
                ('severity_level_expert', models.IntegerField(default=0, verbose_name='Nivel de severidad del experto')),
                ('severity_level_admin', models.IntegerField(default=0, verbose_name='Nivel de severidad del administrador')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_inherents', to='evaluations_krm.evaluationkrminherent', verbose_name='Evaluación de riesgo inherente')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_inherents', to=settings.AUTH_USER_MODEL, verbose_name='Experto')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test', to='risks.riskcompany')),
            ],
            options={
                'verbose_name': 'Test de Riesgo Inherente',
                'verbose_name_plural': 'Tests de Riesgo Inherente',
            },
        ),
        migrations.CreateModel(
            name='RiskCompanyResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('probability_level_residual_administrator', models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Optimizado'), (2, 'Aceptable'), (3, 'Inadecuado'), (4, 'No controlado'), (5, 'N/A')], default=0, verbose_name='Nivel de Control asignado por el Administrador de la compañía')),
                ('description_administrator', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Administrador de la compañía')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_company_residuals', to='evaluations_krm.evaluationkrmresidual', verbose_name='Evaluación de riesgo residual')),
                ('risk_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_company_residuals', to='risks.riskcompany')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo Compañía Residual Agregado',
                'verbose_name_plural': 'Evaluaciones de Riesgo Compañía Residual Agregados',
            },
        ),
    ]
