# Generated by Django 4.1 on 2022-10-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationkrminherent',
            name='status',
            field=models.CharField(choices=[('EP', 'En proceso'), ('FI', 'Finalizado')], default='EP', max_length=2, verbose_name='Estado'),
        ),
    ]
