# Generated by Django 4.1 on 2022-12-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskcompanyresidual',
            options={'verbose_name': 'Evaluación de Riesgo Residual Agregada', 'verbose_name_plural': 'Evaluaciones de Riesgo Residual Agregadas'},
        ),
    ]
