# Generated by Django 4.1 on 2022-10-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0003_alter_risktestinherent_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risktestinherent',
            old_name='probabilityimpact_level_administrator',
            new_name='probability_level_administrator',
        ),
    ]
