# Generated by Django 4.1 on 2022-10-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0004_rename_probabilityimpact_level_administrator_risktestinherent_probability_level_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktestinherent',
            name='impact_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No aplica'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto indicado por el Administrador del Dominio de Riesgo'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='impact_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No aplica'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto indicado por el Experto del Dominio de Riesgo'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='probability_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No aplica'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Probabilidad indicado por el Administrador del Dominio de Riesgo'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='probability_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No aplica'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Probabilidad indicado por el Experto del Dominio de Riesgo'),
        ),
    ]
