# Generated by Django 4.1.3 on 2025-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0005_alter_evaluationkrminherent_certification_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risktestinherent',
            name='impact_branding_level_expert',
        ),
        migrations.RemoveField(
            model_name='risktestinherent',
            name='impact_continuity_level_expert',
        ),
        migrations.RemoveField(
            model_name='risktestinherent',
            name='impact_economic_level_expert',
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='event_speed_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Velocidad de ocurrencia indicado por el Experto asignado al Riesgo N2'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_dedication_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto en el tiempo de dedicación del Comité de Dirección indicado por el Experto asignado al Riesgo N2'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_economic_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto Económico indicado por el Experto asignado al Riesgo N2'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_objectives_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto en los objetivos estratégicos por el Experto asignado al Riesgo N2'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_regulatory_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto Regulatorio indicado por el Experto asignado al Riesgo N2'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_reputational_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto Reputacional indicado por el Experto asignado al Riesgo N2'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='impact_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto indicado por el Administrador de la Evaluación'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='impact_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto indicado por el Experto asignado al Riesgo N2'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='probability_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=0, verbose_name='Nivel de Probabilidad indicado por el Administrador de la Evaluación'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='probability_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=0, verbose_name='Nivel de Probabilidad indicado por el Experto asignado al Riesgo N2'),
        ),
    ]
