# Generated by Django 4.1 on 2022-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0006_alter_risktestinherent_impact_level_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Estado'),
        ),
    ]
