# Generated by Django 4.1 on 2022-10-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0008_alter_risktestinherent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktestinherent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Experto de Dominio de Riesgo'), (2, 'Esperando al Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado'),
        ),
    ]
