# Generated by Django 4.1.3 on 2025-03-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0008_alter_risktestinherent_event_speed_level_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktestinherent',
            name='event_speed_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], default=0, verbose_name='Nivel de Velocidad de ocurrencia indicado por el Evaluador'),
        ),
    ]
