# Generated by Django 4.1 on 2022-10-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0009_alter_risktestinherent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_branding_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto en Imagen indicado por el Experto del Dominio de Riesgo'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_continuity_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto en Continuidad indicado por el Experto del Dominio de Riesgo'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='impact_economic_level_expert',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Impacto Económico indicado por el Experto del Dominio de Riesgo'),
        ),
    ]
