# Generated by Django 4.1.3 on 2025-04-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0009_alter_risktestinherent_event_speed_level_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risktestinherent',
            old_name='severity_level_admin',
            new_name='severity_level_administrator',
        ),
        migrations.RemoveField(
            model_name='risktestinherent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='risktestinherent',
            name='description_admin',
        ),
        migrations.RemoveField(
            model_name='risktestresidual',
            name='probability_level_residual_evaluator',
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='description_administrator',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la valoración del Administrador de compañía'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='description_expert',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la valoración del Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='event_speed_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], default=0, verbose_name='Nivel de Velocidad de ocurrencia indicado por el Administrador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='event_speed_level_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], default=0, verbose_name='Nivel de Velocidad de ocurrencia indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_dedication_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto en el tiempo de dedicación del Comité de Dirección indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_economic_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto Económico indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto indicado por el Administrador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_level_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_objectives_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto en los objetivos estratégicos por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_regulatory_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto Regulatorio indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='impact_reputational_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Nivel de Impacto Reputacional indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='probability_level_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=0, verbose_name='Nivel de Probabilidad indicado por el Administrador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='probability_level_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=0, verbose_name='Nivel de Probabilidad residual indicado por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='severity_level_administrator',
            field=models.IntegerField(default=0, verbose_name='Nivel de severidad del administrador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='severity_level_evaluator',
            field=models.IntegerField(default=0, verbose_name='Nivel de severidad indicado por el Evaluador'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='severity_level_expert',
            field=models.IntegerField(default=0, verbose_name='Nivel de severidad indicado por el Evaluador'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Evaluador de Riesgo Inherente'), (2, 'Esperando al Administrador de compañía'), (3, 'Finalizado')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='risktestresidual',
            name='description_evaluator',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la valoración del Evaluador'),
        ),
        migrations.AlterField(
            model_name='risktestresidual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Evaluador de Riesgo Residual'), (2, 'Esperando al Administrador de compañía'), (3, 'Finalizado')], default=0, verbose_name='Estado'),
        ),
    ]
