# Generated by Django 4.1.3 on 2025-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0010_rename_severity_level_admin_risktestinherent_severity_level_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestresidual',
            name='description_administrator',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la valoración del Administrador de compañía'),
        ),
    ]
