# Generated by Django 4.1 on 2022-10-22 18:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risks', '0023_alter_riskcompany_description'),
        ('companies', '0011_alter_company_controls'),
        ('evaluations_krm', '0010_risktestinherent_impact_branding_level_expert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationKrmResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('date_begin', models.DateField(verbose_name='Inicio de Evaluación')),
                ('date_end', models.DateField(verbose_name='Fin de la Evaluación')),
                ('certification_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Año de certificación')),
                ('certification_period', models.CharField(blank=True, max_length=140, null=True, verbose_name='Periodo de certificación')),
                ('status', models.CharField(choices=[('EP', 'En proceso'), ('FI', 'Finalizado')], default='EP', max_length=2, verbose_name='Estado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_residual_krm', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evaluación Residual KRM',
                'verbose_name_plural': 'Evaluaciones Residuales KRM',
            },
        ),
        migrations.CreateModel(
            name='RiskTestResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Experto de Dominio de Riesgo'), (2, 'Esperando al Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_inherents', to='evaluations_krm.evaluationkrmresidual', verbose_name='Evaluación de riesgo residual')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_residuals', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_test_residual', to='risks.riskcompany')),
            ],
            options={
                'verbose_name': 'Test de Riesgo Residual',
                'verbose_name_plural': 'Tests de Riesgo Residual',
            },
        ),
    ]
