# Generated by Django 4.1.3 on 2025-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0011_risktestresidual_description_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='severity_administrator_qualitative',
            field=models.CharField(choices=[('SE', 'Sin establecer'), ('MB', 'Muy baja'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('MA', 'Muy alta')], default='SE', max_length=2, verbose_name='Severidad cualitativa indicada por el Administrador'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='severity_expert_qualitative',
            field=models.CharField(choices=[('SE', 'Sin establecer'), ('MB', 'Muy baja'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('MA', 'Muy alta')], default='SE', max_length=2, verbose_name='Severidad cualitativa indicada por el Evaluador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='severity_administrator_qualitative',
            field=models.CharField(choices=[('SE', 'Sin establecer'), ('MB', 'Muy baja'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('MA', 'Muy alta')], default='SE', max_length=2, verbose_name='Severidad cualitativa indicada por el Administrador'),
        ),
        migrations.AddField(
            model_name='risktestresidual',
            name='severity_evaluator_qualitative',
            field=models.CharField(choices=[('SE', 'Sin establecer'), ('MB', 'Muy baja'), ('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('MA', 'Muy alta')], default='SE', max_length=2, verbose_name='Severidad cualitativa indicada por el Evaluador'),
        ),
    ]
