# Generated by Django 4.1 on 2022-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0011_evaluationkrmresidual_risktestresidual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationkrminherent',
            name='description',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la realización o supervisión del control'),
        ),
    ]
