# Generated by Django 4.1.3 on 2025-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0012_risktestinherent_severity_administrator_qualitative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktestinherent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'En espera del Evaluador'), (2, 'En esperal del Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='risktestresidual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'En espera del Evaluador'), (2, 'En espera del Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado'),
        ),
    ]
