# Generated by Django 4.1 on 2022-10-23 18:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0012_alter_evaluationkrminherent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='description',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación del test de riesgo inherente'),
        ),
        migrations.AlterField(
            model_name='evaluationkrminherent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
    ]
