# Generated by Django 4.1 on 2022-10-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0013_risktestinherent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='description_admin',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Administrador de la Compañía Evaluada'),
        ),
        migrations.AlterField(
            model_name='risktestinherent',
            name='description',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Experto del Dominio de Riesgo asociado'),
        ),
    ]
