# Generated by Django 4.1 on 2022-10-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0014_risktestinherent_description_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestresidual',
            name='probability_level_residual_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Probabilidad residual indicado por el Evaluador del Dominio de Riesgo'),
        ),
    ]
