# Generated by Django 4.1.3 on 2025-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0014_alter_risktestinherent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
    ]
