# Generated by Django 4.1 on 2022-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0016_alter_risktestresidual_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktestresidual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando al Evaluador de Dominio de Riesgo'), (2, 'Esperando al Administrador'), (3, 'Finalizado')], default=0, verbose_name='Estado'),
        ),
    ]
