# Generated by Django 4.1 on 2022-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0018_risktestresidual_description_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestresidual',
            name='probability_level_residual_administrator',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Probabilidad residual indicado por el Admnistrador de la compañía'),
        ),
        migrations.AlterField(
            model_name='risktestresidual',
            name='description_evaluator',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Administrador de la compañía'),
        ),
    ]
