# Generated by Django 4.1 on 2022-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0019_risktestresidual_probability_level_residual_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestresidual',
            name='description_administrator',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Administrador de la compañía'),
        ),
        migrations.AlterField(
            model_name='risktestresidual',
            name='description_evaluator',
            field=models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Evaluador del Dominio de Riesgo asociado'),
        ),
    ]
