# Generated by Django 4.1 on 2022-11-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0023_alter_riskcompany_description'),
        ('evaluations_krm', '0020_risktestresidual_description_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risktestresidual',
            name='description_administrator',
        ),
        migrations.RemoveField(
            model_name='risktestresidual',
            name='probability_level_residual_administrator',
        ),
        migrations.CreateModel(
            name='RiskCompanyResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('probability_level_residual_administrator', models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto'), (4, 'Crítico'), (5, 'Sin establecer')], default=5, verbose_name='Nivel de Control asignado por el Administrador de la compañía')),
                ('description_administrator', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la evaluación por el Administrador de la compañía')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_company_residuals', to='evaluations_krm.evaluationkrmresidual', verbose_name='Evaluación de riesgo residual')),
                ('risk_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_company_residuals', to='risks.riskcompany')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo Compañía Residual Agregado',
                'verbose_name_plural': 'Evaluaciones de Riesgo Compañía Residual Agregados',
            },
        ),
    ]
