# Generated by Django 4.1 on 2022-11-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0021_remove_risktestresidual_description_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompanyresidual',
            name='probability_level_residual_administrator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Optimizado'), (2, 'Aceptable'), (3, 'Inadecuado'), (4, 'No controlado'), (5, 'N/A')], default=0, verbose_name='Nivel de Control asignado por el Administrador de la compañía'),
        ),
    ]
