# Generated by Django 4.1 on 2022-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0022_alter_riskcompanyresidual_probability_level_residual_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktestresidual',
            name='probability_level_residual_evaluator',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Optimizado'), (2, 'Aceptable'), (3, 'Inadecuado'), (4, 'No controlado'), (5, 'N/A')], default=0, verbose_name='Nivel de Probabilidad residual indicado por el Evaluador del Dominio de Riesgo'),
        ),
    ]
