# Generated by Django 4.1 on 2022-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_krm', '0023_alter_risktestresidual_probability_level_residual_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktestinherent',
            name='severity_level_admin',
            field=models.IntegerField(default=0, verbose_name='Nivel de severidad del administrador'),
        ),
        migrations.AddField(
            model_name='risktestinherent',
            name='severity_level_expert',
            field=models.IntegerField(default=0, verbose_name='Nivel de severidad del experto'),
        ),
    ]
