# Generated by Django 4.1 on 2022-11-20 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations_krm', '0024_risktestinherent_severity_level_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationkrminherent',
            name='admin_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador que ha supervisado la evaluación'),
        ),
        migrations.AddField(
            model_name='evaluationkrmresidual',
            name='admin_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador que ha supervisado la evaluación'),
        ),
    ]
