# Generated by Django 4.1 on 2022-11-30 05:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('date_begin', models.DateField(verbose_name='Inicio de Evaluación')),
                ('date_end', models.DateField(verbose_name='Fin de la Evaluación')),
                ('certification_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Año de certificación')),
                ('certification_period', models.CharField(blank=True, max_length=140, null=True, verbose_name='Periodo de certificación')),
                ('status', models.CharField(choices=[('EP', 'En proceso'), ('FI', 'Finalizado')], default='EP', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Evaluación de Cuestionario',
                'verbose_name_plural': 'Evaluaciones de Cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Ref')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Número de pregunta dentro del cuestionario')),
                ('title', models.CharField(max_length=200, verbose_name='Enunciado')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('title', models.CharField(help_text='Enunciado copiado de la pregunta', max_length=200, verbose_name='Enunciado')),
                ('answer', models.PositiveSmallIntegerField(choices=[(0, 'Sin establecer'), (1, 'Si'), (2, 'No'), (3, 'No aplica')], default=0, verbose_name='Respuesta')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Sin iniciar'), (1, 'Esperando respuesta del evaluador'), (2, 'Finalizado')], default=0, verbose_name='Estado')),
                ('description', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Texto complementario a la respuesta')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tests', to='questionnaires.evaluationquestionnaire', verbose_name='Evaluación de cuestionario')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tests', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_tests', to='questionnaires.question')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaire', verbose_name='Cuestionario'),
        ),
        migrations.AddField(
            model_name='evaluationquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='questionnaires.questionnaire', verbose_name='Cuestionario'),
        ),
    ]
