# Generated by Django 4.1 on 2022-12-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_alter_question_options_remove_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='ref',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ref'),
        ),
    ]
