# Generated by Django 4.1 on 2022-12-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_alter_questionnaire_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontest',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_tests', to='questionnaires.scope', verbose_name='Alcance'),
            preserve_default=False,
        ),
    ]
