# Generated by Django 4.1 on 2022-11-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_evaluationquestionnaire_questiontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationquestionnaire',
            name='company',
        ),
    ]
