# Generated by Django 4.1 on 2022-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_remove_evaluationquestionnaire_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.CharField(max_length=2000, unique=True, verbose_name='Ref'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=5000, verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ref',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Ref'),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='title',
            field=models.CharField(help_text='Enunciado copiado de la pregunta', max_length=5000, verbose_name='Enunciado'),
        ),
    ]
