# Generated by Django 4.1 on 2022-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_alter_question_ref_alter_question_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='question',
            name='concession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Concesión'),
        ),
        migrations.AddField(
            model_name='question',
            name='delegation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Delegación'),
        ),
    ]
