# Generated by Django 4.1 on 2022-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_question_area_question_concession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ref',
            field=models.CharField(max_length=2000, verbose_name='Ref'),
        ),
    ]
