# Generated by Django 4.1 on 2022-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_alter_question_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ref',
            field=models.CharField(max_length=200, verbose_name='Ref'),
        ),
    ]
