# Generated by Django 4.1 on 2022-12-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_alter_questionnaire_name_alter_questionnaire_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=5000, verbose_name='Enunciado'),
        ),
    ]
