# Generated by Django 4.1 on 2022-12-06 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0009_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_to_assign',
            field=models.ManyToManyField(blank=True, related_name='questions_to_assign', to=settings.AUTH_USER_MODEL, verbose_name='Posibles respondedores'),
        ),
    ]
