version: "3"

volumes:
  krm_local_postgres_data: {}
  krm_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: krm_dev_django
    # depends_on:
      # - postgres
      # - redis
    volumes:
      - C://Proyectos/krm-kpmg:/data
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
      - ./.envs/.dev/.email
      - ./.envs/.dev/.ubuntu
    ports:
      - "8000:8000"
    command: /start

  # celeryworker:
  #   <<: *django
  #   image: krm_local_celeryworker
  #   depends_on:
  #     - django
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: krm_local_celerybeat
  #   depends_on:
  #     - django
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: krm_local_flower
  #   depends_on:
  #     - django
  #   ports:
  #     - "5555:5555"
  #   command: /start-flower

  # redis:
  #   image: 'redis:alpine'
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   volumes:
  #     - ./compose/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   expose:
  #     - "6379"

  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./compose/dev/postgres/Dockerfile
  #   image: krm_local_postgres
  #   volumes:
  #     - krm_local_postgres_data:/var/lib/postgresql/data
  #     - krm_local_postgres_data_backups:/backups
  #   env_file:
  #     - ./.envs/.dev/.postgres
