version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: krm_dev_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
      - ./.envs/.dev/.email
      - ./.envs/.dev/.ubuntu
    ports:
      - "8000:8000"
    command: /start

  celeryworker:
    <<: *django
    image: krm_local_celeryworker
    depends_on:
      - redis
      - django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: krm_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: krm_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  redis:
    image: 'redis:alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./compose/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"
