# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Image registry
image:
  registry: ""

# Recursos asignados al contenedfor
container:
  port: 6379
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 500Mi
  image:
    pullPolicy: IfNotPresent #Always
  deployment:
    strategy: Rolling
  probes:
    port: 6379
    # ready:
    #   path: /ht/startup-probe/
    #   initialDelaySeconds: 60
    #   periodSeconds: 10
    #   timeoutSeconds: 5
    # live:
    #   path: /ht/liveness-probe/
    #   initialDelaySeconds: 60
    #   periodSeconds: 10
    #   timeoutSeconds: 5

# Service svc
service:
  application:
    type: LoadBalancer
    sessionAffinity: None
  # management:
  #   type: ClusterIP
  #   sessionAffinity: None

# Config Maps
configmaps:
  create: false
  values:

# Secrets
secrets:
  create: false
  # values:
    # KEY: "value"

# Listado de volumenes a montar en el contenedor
volumes:
  create: true
  list:
    volumeName: redis-resources-pv
    claimName: resources-claim-redis
    accessModes:
      ReadOnlyMany
    mounts:
      mountPath: /usr/local/etc/redis/redis.conf
      subPath: redis.conf