BBBB BBBB


BB BBBBBBBBBBBBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
  XXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
      XXXX gettext(u'REF') XXXXX
      XXXX gettext(u'Fecha inicio') XXXXX
      XXXX gettext(u'Fecha fin') XXXXX
      XXXX gettext(u'Estado') XXXXX
      XXXX gettext(u'¿Quién debe responder?') XXXXX
      XXXX gettext(u'Responsable') XXXXX
      XXXX gettext(u'Supervisor') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
      BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
      XXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFXXFFFFFFFFFFFFXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFXXFFFFFFFFFFFFXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      BBBBBB
  XXXXXXXX
XXXXXXXX
BBBB
  XX XXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Sin resultados') 
  XXXX
BBBBB
