XXXXXXXXXXXXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
	XXXXXXXXXXXXXX XXXXXX
	XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
		XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
			XXXXXXXXXXXXX XXXXXXX
			XXX XXXXXXXXXXXXXXX XXXXXXXXX
				XX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
			XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXXXXX
			XXX XXXXXXXXXXXXXXX XXXXXXXXX
				XX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
			XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXXXXX
			XXX XXXXXXXXXXXXXXX XXXXXXXXX
				XX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
			XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXXXXX
			XXX XXXXXXXXXXXXXXX XXXXXXXXX
				XX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
			XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXXXXX
			XXX XXXXXXXXXXXXXXX XXXXXXXXX
				XX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
			XXXXXXXXXXX XXXXXXX
		XXXXX
	XXXXXX
	XXXXXXXXXXXX XXXXXX
	XXXXXXXXXXXXX XXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX
		XXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXX XXXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXXXXXXXXX XXXXXXX
	XXXXXX
	XXXXXXXXXXX XXXXXXXXXX
XXXXXX
XXXXXXXXXXXXX XXXXXXX