BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Datos del Control') X XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo de control') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Frecuencia') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Key control') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXX _("Si, No") XXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'ELC') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXX _("Si, No") XXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX
          XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Alcance') XXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX            
            BB BBBBBBBBBBBBBBBBBBB
              BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX
                  XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  BBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
              BBBBBB
                
            BBBB
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sin riesgos asociados') XXXXXXXXXXXXX
              XXXXXX
            BBBBB 
          XXXXXX
          XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Riesgos (N2)') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX            
            BB BBBBBBBBBBBBBBBBBBB
              BBB BBBB BB BBBBBBBBBBBBBBBBB
                BB BBB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX
                  XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  BBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
              BBBBBB
                
            BBBB
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sin riesgos asociados') XXXXXXXXXXXXX
              XXXXXX
            BBBBB 
          XXXXXX
          XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Subprocesos') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX            
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX
                  XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  BBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
              BBBBBB
                
            BBBB
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sin subprocesos asociados') XXXXXXXXXXXXX
              XXXXXX
            BBBBB
          XXXXXX   
        XXXXXXXXXXX
      XXXXXX
      
    XXXXXX

    XXXX XXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Objetivo') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Automatización') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sistemas') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Planta') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Evidencia') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Plan de Testeo') XXXXXXXXXXXXX
            XXXXXFFFFXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'GAP') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Existencia') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Integridad') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Presentación') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Valoración') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Obligación') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Precisión') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fraude') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Editar') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Eliminar') XXXX
      XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB