BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Riesgos (N1) / Procesos') 
          XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Riesgos (N2) / Subprocesos') 
          XXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Evidencia') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Frecuencia') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Tipo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Automático') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'ELC') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Key Control') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Riesgos (N2)') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Subprocesos') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBB BB BBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBB BB BBBB
            XXXXXXXXXX
            BBBB
            XXXXXXX
            BBBBBXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
              XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXFFFFFFXXXXXXX
                XXXXXX
                XXXX XX X XXXXXXXXXXXXXXXX
                  BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXX
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXX
                    XXXX
                  BBBBBB
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XX X XXXXXXXXXXXXXXXX
                  BBB BB BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXX
                    XXXX
                  BBBBBB
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XX X XXXXXXXXXXXXXXXX
                BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXX
                BBBBBB
                XXXXXX
              XXXXXX
            XXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Nuevo') XXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Descagar Controles') XXXXXXXXX
    XXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
