BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXX XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X

    XXX XXXXXXXXX X X
      XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXX
        XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X
            XXXXXXXXX X
              XXX XXXXX
              XXXXXXXX XXXX
            X
          X
        X
        XXXXXXXXXXXX XX X
          XX XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXX XX X
        XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
      X
    XX
  XXX

XXXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
            XXXXXXXX gettext(u'Datos del Control') XXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX
                XXXXXXXXXX
                FFFFFFFFFFFFFFF
                XXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX
                XXXXXXXXXX
                FFFFFFFFFFFFFFF
                XXXXXXXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXXXXXX gettext(u'Atributos del Control') XXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXX
                XXXXXXXXXX
                  FFFFFFFFFFFFFFF
                  XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXXXXXX gettext(u'Asertions') XXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
            XXXXXX

          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
