BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Dominio de Riesgo') X XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Referencia') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Nombre') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Descripción') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXFFFFXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Editar') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Eliminar') XXXX
      XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Riesgos asociados') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXXX gettext(u'Nombre') XXXXX
          XXX XXXXXXXXXXXX gettext(u'Descripción') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXX
                XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen riesgos asociados a este dominio de riesgo') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Añadir') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB