BBBB BBBB
 gettext(u'Sin asignar') 

XXXXXXX
  XXXXXX X
    XXXXXX XXXXX XXXXXXXXXXX
    XXXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXX XX
    XXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X
XXXXXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
  XXXXXXX
    XXXX
      XXX XXXXXXXXXXXXX gettext(u'REF') XXXXX
      XXXX gettext(u'CONTROL') XXXXX
      XXXX gettext(u'CONTROL OWNER') XXXXX
      XXXX gettext(u'CONTROL SUPERVISOR') XXXXX
      XXXX gettext(u'STATUS') XXXXX
      XXXX gettext(u'RESULTADO') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BB BB BBB
      XXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXXXXXXXXXXXX
          XXXXXXXXX
          XXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              
            BBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX gettext(u'Asignar') XXXX
            BBBBB
          XXXXX
          XXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
              
            BBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX gettext(u'Asignar') XXXX
            BBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBBB
          XXXXX
      XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX
