BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXX
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXX
      XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
          XXXXXXXXX X
            XXX XXXXX
            XXXXXXXX XXXX
          X
        X
      X
      XXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXXX XX X
      XXX

    BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
    BB BBBBBBBBBBBBB BB BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX        XX XXXXXXX XXXXXXX XXXXX XXXXXXX
        XXXXXXXXX XXXXX             XX XX XXX XX XX XXXXXXX
        XXXXXXXXXX XXXXXXXX
      XXX
    BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
      XXX
    BBBBB
  XXX

XXXXXXXXX

BB BBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
BBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Lanzamiento de Evaluaciones de Riesgo Inherente') XXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXX gettext(u'Paso 1: Datos de la Evaluación') XXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX
                FFFFFFFFFFFFFFF
                XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

            XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX XXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
        XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
    XXXXXX

XXXXXX

XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
