BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 

BBBBB BBBBBBBBB

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXXXXXX X XX X XX X XXXXXXXX
      XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX                
      XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX 
      XXXXXXXXXXX XXXXX
    XXX
  XXX

  XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
    
    XX XXXXXXXXXXXX XX XXXXX X
      XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
    X XXXX X
      X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX
    X
    
  X
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB


XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Enviar recordatorio') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Usuario') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Riesgos completados') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Riesgos pendientes') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Notificación') XXXXX
          XXXXX
        XXXXXXXX
        XXXXXXX
          BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBB B B
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBB
                 gettext(u'No hay tareas pendientes') 
              BBBBB
            XXXXX
            XXXX
              
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX
              BBB BBBBB BB BBBBBBBBBBBBBBBB
              XXXX
                  XFFFFFFFFF FFFFFFXXXXXBB BBB BBBBBBBBBBBBXXXXBBBBB
              XXXXX
              BBBBBB
            XXXXX
          XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX

      BB BBBBBBBBBBBBBBBBB BB BBBB

      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Notificar usuarios') 
      XXXXXXXXX

      BBBBB
    XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX

XXXX XXXXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Envío de notificaciones') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'¿Desea enviar una notificación de recordatorio de tareas pendientes a los siguientes usuarios?') 
        XXXXX
          XXXX
          XXX XX XXXXXXXXXXXX
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Enviar notificaciones') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX

BBBBBBBB BBBBBBB
