BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BB BBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
BBBBB


XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XX XXX
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXX XX XX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXX XX XX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXX XX XXX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X
      X
      XXXX X
        XXX XXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXX XXXXXX

            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXX XX XXXXXXXXXXXXX XXX XXX

            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXX XX XXXXXXXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXX
                XX XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXX XXXXXX
            X
          XXX
        X
      X
      XXXXXX XXXXX
    XX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
  X
XXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          
        XXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                        XXXXXXX
                      XXXXXX
                      BBBBB
                      XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sociedades en alcance') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBB BB BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Año de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Periodo de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de fin') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXX XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBB
    BBB BB BB BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
       gettext(u'Algún riesgo no ha sido evaluado todavía por su evaluador asignado, no puede recuperar su valoración') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXXX
                    XXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Datos del Riesgo') XXXXXXXXX XXX
                    XXXX XXXXXXXXXX XXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominio de Riesgo') XXXXXXXXXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Riesgo Maestro') XXXXXXXXXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
                    XXXXXFFFFXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Principales elementos') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Principales eventos') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Actividad afectada') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Personal expuesto') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXX
                  XXXX XXXXXXXXXX XXXXXXXX
                    XXX XXXXXXXXXXXXX gettext(u'Valoración aportada por el Evaluador de Riesgo Inherente del Riesgo N2') XXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXX
                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Probabilidad') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Remoto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Posible') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Prácticamente cierto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto económico') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto en los Objetivos Estratégicos') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Velocidad de ocurrencia') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy baja') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Baja') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Media') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alta') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alta') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto Reputacional') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBBX XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBBX XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto Regulatorio') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto en el Tiempo de dedicación') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Descripción de la valoración del Evaluador de Riesgo Inherente del Riesgo N2') XXXXX
                        XXXX XXXXXXXXXXXX
                          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFXXFFFFFFFFFFFFFFFFFFF FF FF FFFFFFFF FFFFFFF FFFFFFFFFF FFF FFFFF FFF FFFFFFFFFFXXXX
                        XXXXXX
                      XXXXXX
                    XXXXXX

                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBB

    XXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Finalizar evaluación') XXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFFFFFFFFFFF
              XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
                       gettext(u'Si, como administrador de compañía, deja algún campo de algún riesgo sin valorar, se tomarán en cuenta los valores dados por los usuarios evaluadores.') 
                    XXXXXX
                  XXXXXX
                  XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                   gettext(u'Usar la valoración dada por los evaluadores para los campos no completados') 
                XXXXXXXX
              XXXXXX

              XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Finalizar evaluación') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Actualizando...') XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
              XXXXXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

BBBB
  XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen tests de riesgo inherente pendientes para esta Evaluación') X
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
