BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BB BBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
BBBBB

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XX XXX
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXX XX XX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXX XX XX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXX XX XXX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXX
            X
          XXX
        X
      X
      XXXX X
        XXX XXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX
            XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXX XXXXXX

            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXX XX XXXXXXXXXXXXX XXX XXX

            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXX XX XXXXXXXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXX
                XX XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXX X XXXXX
              XXXXXX XXXXXX
            X
          XXX
        X
      X
    XX
    XXXXXX XXXXX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

XXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
XX XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          
        XXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                        XXXXXXX
                      XXXXXX
                      BBBBB
                      XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sociedades en alcance') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBB BB BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXX
                    BBBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Año de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Periodo de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de fin') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXX XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBB
    BBB BB BB BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
       gettext(u'Algún riesgo no ha sido evaluado todavía por su evaluador asignado, no puede recuperar su valoración') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX  XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX gettext(u'Datos del riesgo') XXXXX
                  XXXXXX

                  XXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominio de Riesgo') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Riesgo Maestro') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX

                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            FFFFFFFFFFFFF
                          XXXXXX
                        XXXXXX
                      XXXXXX

                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Controles de la compañía asociados') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
                          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
                              XXXXXXX
                                XXX XXXXXXXXXXXXXXXXXX XXXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Evidencia') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Frecuencia') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
                                XXXXX
                              XXXXXXXX
                              XXXXXXX
                                BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                  XXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXX
                                      XXXX XXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXX
                                          FFFFFFFFFFFFFFFFFFFFFFFFF
                                        XXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXX
                                          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                      XXXXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                      XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXFFFFFFXXXXXXX
                                        XXXXXX
                                        XXXX XX X XXXXXXXXXXXXXXXX
                                          BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXX
                                          BBBBBB
                                        XXXXXX
                                      XXXXXX
                                    XXXXX
                                  XXXXX
                                BBBBBB
                              XXXXXXXX
                            XXXXXXXX
                          XXXXXX
                        BBBB
                          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX gettext(u'No existen controles activos en la compañía que mitiguen este riesgo') XXXXXXX
                          XXXXXX
                        BBBBB
                      XXXXXX
                    XXXXXX

                  XXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX gettext(u'Última valoración de Riesgo Inherente') XXXXX
                      XXXXXX
                    XXXXXX

                    BB BBBBBBBBBBBBBBBBBBBBBBBBBB

                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Severidad') XXXXXXXXXXXXXXXXX

                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXX BB BBBBBBBB BB BBBBXXXXXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBBXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXX XXXXXXX
                           XX
                        XXXXXXX
                        BBBBBBB
                      XXXXXX
                    XXXXXX

                    BBBBB

                  XXXXXX

                  BB BBBBBBBBBBBBBBBBBBBBBBBBBB

                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Impacto Inherente') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Probabilidad Inherente') XXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Remoto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Posible') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Muy probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Prácticamente cierto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Velocidad de ocurrencia Inherente') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                      XXXXXX
                    BBBBBBB

                  BBBB

                    XXXX XXXXXXXXXXXX
                      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX gettext(u'No existen tests de Riesgo Inherente asociados a este Riesgo N2') XXXXXXX
                    XXXXXX

                  BBBBB
                XXXXXX
              XXXXXX
            XXXXXX


            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXX
                  XXXX XXXXXXXXXX XXXXXXXX
                    XXX XXXXXXXXXXXXX gettext(u'Valoración aportada por el Evaluador de Riesgo Residual del Riesgo N2') XXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXX
                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Probabilidad') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Remoto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Posible') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Prácticamente cierto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto económico') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto en los Objetivos Estratégicos') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Velocidad de ocurrencia') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy baja') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Baja') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Media') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alta') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alta') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto Reputacional') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto Regulatorio') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Impacto en el Tiempo de dedicación') XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXXXXXXXXXXX BBBBB XXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX gettext(u'Descripción de la valoración del Evaluador de Riesgo Residual del Riesgo N2') XXXXX
                        XXXX XXXXXXXXXXXX
                          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFXX _('No se ha aportado todavía valoración por parte del Evaluador') XXXX
                        XXXXXX
                      XXXXXX
                    XXXXXX

                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBB


    XXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Finalizar evaluación') XXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFFFFFFFFFFF
              XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
                       gettext(u'Si, como administrador de compañía, deja algún campo de algún riesgo sin valorar, se tomarán en cuenta los valores dados por los usuarios evaluadores.') 
                    XXXXXX
                  XXXXXX
                  XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                   gettext(u'Usar la valoración dada por los evaluadores para los riesgos no completados') 
                XXXXXXXX
              XXXXXX

              XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Finalizar evaluación') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Actualizando...') XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
              XXXXXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

BBBB
  XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen tests de riesgo residual pendientes para esta Evaluación') X
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
