BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
  XXXXXXX
    XXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XX
    XXXXXXX XXXXX
  X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXX XXXX
  XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXX XXXX
  XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
X
XXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXX XXXX
  XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXX XXXXXXX XXXXXXXXXXX
  XXXXXXXXX XXXXXXXXX XX XXXXXXXXX XXXX XX XXXXXXX X XXXXXXXX XX XXXXXXX XX
X

XXXXXXXX
XXXXXXXX
  XXX XXXXXXXXXXXXX XXX
  XXXXX XXXXX XXX
  XX XXXXX XX XXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
  X XXXX XX XXXXX XX XXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
  X

  XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX X

    XXXXX XXXX X X
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX X
        X
          XXXXXX XXX
          XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        X
      X
    XX
    XXXXX XXXXXX X X
      XXXXX XXXXXX
      XXXXX XXXXX
      XXXXX X
          XXXXX XXXXXXXXXXX
        XX
      XXXXXXXX X
        XXXXXXXXX X X
          XXXXXXXXX XXXXX
        XX
        XXXXXXXXXXX XXXXX
        XXXXXXXX X
          XXXXXXX X
            XXXXXXXXXXXXXX
          XX
          XXXXXX X
            XXXXXXXX XXXXXX
          XX
          XXXXXXXX X
            XXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXX X
              XXXXXX XXXXXXXXXXXXXXXXXXXXX X
                XXXXXX XXXXXXXXXXXXXXXXXXX
              X
            XX
          XX
        XX
        XX
    XX
    XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  X
XXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'en progreso') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXXX gettext(u'REF') XXXXX
          XXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Riesgos') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX
              BBBBBB
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXX
            XXXXXXXX
              XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBB
                XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
          BBBBBB
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Evaluador') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Administrador') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Finalizados') XXXXXXXXXX
    XXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de riesgo residual en proceso') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Nuevo') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXXX gettext(u'REF') XXXXX
          XXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Riesgos') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX
              BBBBBB
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXX
            XXXXXXXX
              XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBB
                XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
          BBBBBB
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Evaluador') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Administrador') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Finalizados') XXXXXXXXXX
    XXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de riesgo residual finalizadas') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX

BBBBBBBB BBBBBBB
