BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BB BBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
BBBBB


XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXX XXXXXXXXXX X XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XX XXX
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXX XX XX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXX XX XX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXX XXXXX X XXXXXXXXXXXXXX
          XX XXXXXXX XX XXXXXXXXXXXXX XXX XXX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XXXXXX XXXXX
    XX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXX XXXXX XX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXX XXX XXXXXX XX
  X

  XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXX XX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXX XX
  X

  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XX
  X

  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XX
  X

XXXXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
XX XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          
        XXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                        XXXXXXX
                      XXXXXX
                      BBBBB
                      XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sociedades en alcance') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBB BB BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB

                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

                    BBBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Año de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Periodo de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de fin') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXX XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBB
    BBB BB BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX  XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX gettext(u'Datos del riesgo') XXXXX
                  XXXXXX

                  XXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominio de Riesgo') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Riesgo Maestro') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX

                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            FFFFFFFFFFFFF
                          XXXXXX
                        XXXXXX
                      XXXXXX

                    XXXXXX

                    XXXX XXXXXXXXXX XXXXXX

                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Controles de la compañía asociados') XXXXXXXXXXXXX
                      XXXXXX

                      XXXX XXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
                          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
                              XXXXXXX
                                XXX XXXXXXXXXXXXXXXXXX XXXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Evidencia') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Frecuencia') XXXXX
                                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
                                XXXXX
                              XXXXXXXX
                              XXXXXXX
                                BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                  XXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXX
                                      XXXX XXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXX
                                          FFFFFFFFFFFFFFFFFFFFFFFFF
                                        XXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXX
                                          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                      XXXXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                      XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXFFFFFFXXXXXXX
                                        XXXXXX
                                        XXXX XX X XXXXXXXXXXXXXXXX
                                          BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXX
                                          BBBBBB
                                        XXXXXX
                                      XXXXXX
                                    XXXXX
                                  XXXXX
                                BBBBBB
                              XXXXXXXX
                            XXXXXXXX
                          XXXXXX
                        BBBB
                          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX gettext(u'No existen controles activos en la compañía que mitiguen este riesgo') XXXXXXX
                          XXXXXX
                        BBBBB
                      XXXXXX
                    XXXXXX

                  XXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX gettext(u'Última valoración de Riesgo Inherente') XXXXX
                      XXXXXX
                    XXXXXX

                    BB BBBBBBBBBBBBBBBBBBBBBBBBBB

                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Severidad') XXXXXXXXXXXXXXXXX

                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXX BB BBBBBBBB BB BBBBXXXXXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBXXXXXXXXXXXXXXBBBB BBBBBBBB BB BBBBXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXX XXXXXXX
                           XX
                        XXXXXXX
                        BBBBBBB
                      XXXXXX
                    XXXXXX

                    BBBBB

                  XXXXXX

                  BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

                      XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Impacto Inherente') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Muy bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Bajo') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Medio') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Muy alto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Probabilidad Inherente') XXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Remoto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Posible') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Muy probable') XXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Prácticamente cierto') XXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXXX

                      XXXXX
                        XXXX XXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Velocidad de ocurrencia Inherente') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                              XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBX
                              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                      XXXXXX
                    BBBBBBB

                  BBBB

                    XXXX XXXXXXXXXXXX
                      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX gettext(u'No existen tests de Riesgo Inherente asociados a este Riesgo N2') XXXXXXX
                    XXXXXX

                  BBBBB
                XXXXXX
              XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX

          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFX XXXXXXX
          XXXXXX
          XXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
        XXXXXX
      XXXXXX
    BBBBBB

    XXXX XXXX XXX
    XXXX XX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX X  XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Evidencia') XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Frecuencia') XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'ELC') XXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
            XXXXX
          XXXXXXXX
          XXXXXXX
            BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                      FFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX _("Yes, No") XXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXFFFFFFXXXXXXX
                    XXXXXX
                    XXXX XX X XXXXXXXXXXXXXXXX
                      BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXX
                      BBBBBB
                    XXXXXX
                  XXXXXX
                XXXXX
              XXXXX
            BBBBBB
          XXXXXXXX
        XXXXXXXX
        BBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen Entity Level Controls (ELC) para mitigar los riesgos mostrados en esta evaluación') X
          XXXXXX
        BBBBB
        XXXXXX
      XXXXXX
    XXXXXX XXX

    XXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Finalizar evaluación') XXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFFFFFFFFFFF
              XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Finalizar y enviar evaluación para su validación') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
              XXXXXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

BBBB
  XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen tests de riesgo residual pendientes para esta Evaluación') X
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
