BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'pendientes') XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX
             gettext(u'Progreso') 
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX
          XXXXXX
        BBBBB
      XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Número de Riesgos') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBB
                XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
          BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de riesgo residual pendientes') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'entregadas') XXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Número de Riesgos') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBB
                XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
          BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de riesgo residual entregadas') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'finalizadas') XXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Número de Riesgos') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXXFFFFFFFFFFFFXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBB
                XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBB
              XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
          BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de riesgo residual finalizadas') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
