BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BB BBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
BBBBB


XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXX XXXXXXXXXX X XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XX XXX
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXX XX XX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXX XX XX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXX XXXXX X XXXXXXXXXXXXXX
          XX XXXXXXX XX XXXXXXXXXXXXX XXX XXX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
          X
        XXX
      X
      XXXXXX XXXXX
    XX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXX X
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
  X
XXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          
        XXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                        XXXXXXX
                      XXXXXX
                      BBBBB
                      XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sociedades en alcance') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBB BB BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                    BBBBB
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Año de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Periodo de certificación') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de fin') XXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXX XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBB
    BBB BB BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX  XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXXX
                    XXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Datos del Riesgo') XXXXXXXXX XXX
                    XXXX XXXXXXXXXX XXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominio de Riesgo') XXXXXXXXXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Riesgo Maestro') XXXXXXXXXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX
                          XXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                          XXXXXX
                          XXXXX
                            
                          XXXXXX
                        XXXXXX
                      XXXXXX
                      XXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
                    XXXXXFFFFXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Principales elementos') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Principales eventos') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Actividad afectada') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Personal expuesto') XXXXXXXXXXXXX
                        XXXXXFFFFXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFX XXXXXXX
            XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBB

    XXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Finalizar evaluación') XXXXXX
        XXXXXXXXXXXXX XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              FFFFFFFFFFFFFFF
              XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Finalizar y enviar evaluación para su validación') XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
              XXXXXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

BBBB
  XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen tests de riesgo inherente pendientes para esta Evaluación') X
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
