apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "artifact.name" . }}-service
  labels:
    app: {{ include "artifact.name" . }}
    deploymentVersion: {{ .Chart.Version }}
spec:
  type: {{ .Values.service.application.type }}
  sessionAffinity: {{ .Values.service.application.sessionAffinity }}
  ports:
    - name: service
      protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    deployment: {{ include "artifact.name" . }}
    app: {{ include "artifact.name" . }}    
