{{- if .Values.volumes.create -}}
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: resources-claim-redis
#  namespace: {{ .Release.Namespace }}
#  labels:
#    app: {{ include "artifact.name" . }}
#    deploymentVersion: {{ .Chart.Version }}
#  finalizers:
#    - kubernetes.io/pvc-protection
#spec:
#  accessModes:
#    - ReadOnlyMany
#  resources:
#    requests:
#      storage: 10Mi
#  volumeName: {{ .Release.Namespace }}-resources-pv
#  volumeMode: Filesystem
{{- end -}}
