# Generated by Django 2.2.8 on 2020-02-05 17:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creación.', verbose_name='Creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Última modificación.', verbose_name='Última modificación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('vat', models.CharField(blank=True, error_messages={'unique': 'Dicho Vat ya está en uso.'}, max_length=20, null=True, unique=True, verbose_name='CIF')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dirección')),
                ('state', models.CharField(blank=True, max_length=140, null=True, verbose_name='Población')),
                ('cp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Dicho email ya está en uso por otro cliente.'}, max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Grupo empresarial',
                'verbose_name_plural': 'Grupos empresariales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creación.', verbose_name='Creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Última modificación.', verbose_name='Última modificación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('vat', models.CharField(blank=True, error_messages={'unique': 'Dicho Vat ya está en uso.'}, max_length=20, null=True, unique=True, verbose_name='CIF')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dirección')),
                ('state', models.CharField(blank=True, max_length=140, null=True, verbose_name='Población')),
                ('cp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='business_group.BusinessGroup', verbose_name='Grupo empresarial al que pertenece')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ['name'],
            },
        ),
    ]
