BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'FECHA DE VENCIMIENTO DEL PLAN DE REMEDIACIÓN') X XXXXXXX XXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'FICHERO ADJUNTO') X XXXXXXX
      BB BBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXX XXXXXXX  gettext(u'Descargar adjunto') XXXX

      BBBB
         gettext(u'No se ha adjuntado ningún fichero') 
      BBBBBXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'DESCRIPCIÓN') X XXXXXXX XXXX
      FFFF
    XXXXXX
  XXXXXX
XXXXXX
