# Generated by Django 4.1 on 2022-08-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=140, verbose_name='Nombre de la aplicación')),
                ('main_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email principal')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
                'ordering': ['app_name'],
            },
        ),
    ]
