# Generated by Django 4.1 on 2022-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_emails',
            field=models.BooleanField(default=False, verbose_name='Habilitar envío de emails'),
        ),
    ]
