# Generated by Django 4.1.3 on 2024-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_enable_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='main_email',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Email principal'),
        ),
    ]
