# Generated by Django 4.1.3 on 2024-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_configuration_main_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_delete_files_ct',
            field=models.BooleanField(default=False, verbose_name='Habilitar eliminación de archivos en los Tests de Control'),
        ),
    ]
