# Generated by Django 4.1.3 on 2024-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_configuration_enable_delete_files_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_questionnaires',
            field=models.BooleanField(default=False, verbose_name='Habilitar apartado de cuestionarios'),
        ),
    ]
