# Generated by Django 4.1.3 on 2024-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_configuration_enable_questionnaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='control_without_risk',
            field=models.BooleanField(default=False, verbose_name='Obligar a que al crear un control se asocie a un riesgo'),
        ),
    ]
