BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
  X
XXXXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
            XXXXXXXXXX
              XXXXXXXX gettext(u'Datos de la Compañía') XXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              BB BBBBBBBBB
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXX XXXXXX XXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                XXXXXX
              BBBBB
            XXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
