BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXXXXX XXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Compañía') X XXXXXXX XXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX XXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Dominio de Riesgo') X XXXXXXX XXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXXX
    
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Asignar') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Volver') XXXXXXXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB