BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Datos de la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Nombre') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'País') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                XXXXXXXXXXXXX
                BBBBB
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Alcance societario') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBB
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'CIF') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Email') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dirección') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Población') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Código postal') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXXXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Editar') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXX
          XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Usuarios de la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
              XXXX gettext(u'Email') XXXXX
              XXXX gettext(u'Nombre') XXXXX
              XXXX gettext(u'Apellidos') XXXXX
              XXXX gettext(u'Cargo') XXXXX
              XXXX gettext(u'Último inicio de sesión') XXXXX
            XXXXX
          XXXXXXXX
          XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
            XXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXFFFFFFFFFFFFFFFFFFXXXXX
              XXXXFFFFFFFFFFFFFFFFFFXXXXX
              XXXXFFFFFFFFFFFFFFFFFFXXXXX
              XXXXFFFFFFFFFFFFFFFFFFXXXXX
              XXXXFFFFFFFFFFFFFFFFFFF FF FFFFFFFF FFFFFF FFFFFFFFXXXXX
            XXXXX
            BBBBBB
          XXXXXXXX
        XXXXXXXX
        BBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen usuarios en la compañía') XXXXXXX
        BBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Evaluadores de Cuestionarios') XXXXXXXXXXXXXXX
          XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXX gettext(u'Email') XXXXX
                XXXX gettext(u'Nombre') XXXXX
                XXXX gettext(u'Apellidos') XXXXX
                XXXX gettext(u'Último inicio de sesión') XXXXX
              XXXXX
            XXXXXXXX
            XXXXXXX
              BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBB
              XXXX
                XXXXFFFFFFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFFFFFFF FF FFFFFFFF FFFFFF FFFFFFFFXXXXX
              XXXXX
              BBBBBB
            XXXXXXXX
          XXXXXXXX
          BBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen usuarios en la compañía') XXXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Evaluadores de Riesgo (RI) de la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
              XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
                  XXXX gettext(u'Referencia') XXXXX
                  XXXX gettext(u'Riesgo N2') XXXXX
                  XXXX gettext(u'Evaluador (RI) asignado') XXXXX
                XXXXX
              XXXXXXXX
              XXXXXXX
                BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX
                    XXX XXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXX
                      BB BBB BBBBBBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                      BBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX  XXXXXXXXXXXXXXX
                      BBBBB
                    XXXXX
                  XXXXX
                BBBBBB
              XXXXXXXX
            XXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Evaluadores de Riesgo (RR) de la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
              XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
                  XXXX gettext(u'Referencia') XXXXX
                  XXXX gettext(u'Riesgo N2') XXXXX
                  XXXX gettext(u'Evaluador (RR) asignado') XXXXX
                XXXXX
              XXXXXXXX
              XXXXXXX
                BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
                XXXX
                  XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXX
                          XXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXX
                    BB BBB BBBBBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBB
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX  XXXXXXXXXXXXXXX
                    BBBBB
                  XXXXX
                XXXXX
                BBBBBB
              XXXXXXXX
            XXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Riesgos que aplican en la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

              XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'REF') XXXXX
                    XXX XXXXXXXXXXXX gettext(u'Nombre') XXXXX
                    XXX XXXXXXXXXXX gettext(u'Descripción') XXXXX
                    XXX XXXXXXXXXXX gettext(u'Principales elementos') XXXXX
                    XXX XXXXXXXXXXX gettext(u'Principales eventos') XXXXX
                    XXX XXXXXXXXXXX gettext(u'Actividad afectada') XXXXX
                    XXX XXXXXXXXXXX gettext(u'Personal expuesto') XXXXX
                    XXXX gettext(u'Dominio de Riesgo') XXXXX
                    XXXX gettext(u'Riesgo Maestro (N1)') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Controles') XXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
              XXXXXXXX
            BBBB
              XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen Riesgos (N2) que apliquen sobre esta compañía') XXXXXXX
            BBBBB
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX
           gettext(u'Editar lista de riesgos que aplican') XXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Controles y responsables que aplican en la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXX
            XXXXXXXXX gettext(u'Controles activos de la compañía') XXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'¿Aplica?') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Responsables') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Supervisores') XXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                      XXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFFFFFFFFFFFF
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sí') XXXXXXX
                        BBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'No') XXXXXXX
                        BBBBB
                      XXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXBB BBB BBBBBBBBBBBBXXXXBBBBB
                        BBBBBB
                      XXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXBB BBB BBBBBBBBBBBBXXXXBBBBB
                        BBBBBB
                      XXXXX
                    XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Controles inactivos de la compañía') XXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'¿Aplica?') XXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                      XXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFFFFFFFFFFFF
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXX
                        XXXXXX
                      XXXXX
                      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sí') XXXXXXX
                        BBBB
                          XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'No') XXXXXXX
                        BBBBB
                      XXXXX
                    XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX

          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX


XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
