BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXXX
    XXX XXXXXXXXXXX X XXX
    XXX XXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXX       XX XXXXXX XXXXXXXXXX
                XXXXXXXXXXXXX XXX     XX XXXXXX XX XXXX XXX XXXX
                XXXXXXXXXXXXX XXX XXX XXX XXXX XX XXXXXX XXX XXXX XXXXXX XXXX XXXXXXX
                XXXXXX
                  XXXXXXXX X
                  XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
                  XXX X
                  XXXXXXXXXXXXXXXXXXXXXXXX X
                  XXXXXXXX X
                  XXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
                  XXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
                  XXX
              XXX
            XXXXXXXXXXXXXXXXXXX
        XXX

        XX XXXXXX XXXXXX XXXXX XX XXXX XXX XXXXXXXX XXXXXXXXXX XXXXXX XXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXX X XXX

            XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX X
              XX XXXXXXX XXXXXXX XXXX XXXX
              XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXXXXXXXX XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXX XXXX XXXXXXX XXXXXXXXX

                XX XXXX XXX XXXXX XXXXXXXX XXXXXXXXXX XX XXX XXXXXXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXX XX XX XX XXX XXXXX XXXXXX
                    XX X XXXXXXXXXXXXXXXXX
                    XX X XXXXXXXXXXXXXXXXXXX XXXX
                    XXXXXXXXXXXXXXXXXXXXX
                XXX
              X
          XXX

          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Riesgos (N2) que aplican a la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX
                BBB BBBB BBBBBBBBBBB BB BBBBBBBBB
                XXXXXXXXXXXXXXXX XX XXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX
                    XXXXXXX
                      XXXX
                        XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'REF') XXXXX
                        XXX XXXXXXXXXXXX gettext(u'Nombre') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Descripción') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Principales elementos') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Principales eventos') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Actividad afectada') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Personal expuesto') XXXXX

                        XXXX gettext(u'Riesgo Maestro (N1)') XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Controles') XXXXX
                      XXXXX
                    XXXXXXXX
                    XXXXXXX
                      BBB BB BB BBBBBBBBBBBBBBBBB
                        XXXX
                          XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                      BBBBBB
                    XXXXXXXX
                  XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  BBBBBB
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
