BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
        XX XXXX XXXXXX XX XXXXXXX XXXXXXX XXXXXXX XXXXXX X XXXXXXXXXXXX XXXX XX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXX XXXXXX XXX
    XXXXXX
    XXXX XXXXXXXXX XXXXXX XXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXX XXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXX XXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Control') XXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXX XXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXX XXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'¿Aplica para esta compañía?') XXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXFFFFFFFFFFFFFFFXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Control Owners') XXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXFFFFFFFFFFFFFFFXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Supervisores') XXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXX XXX
              XXXX XXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXFFFFFFFFFFFFFFFXXXXXX
              XXXXXX
              XXXX XXXXXXXX XXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXX XXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Asignar') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Volver') XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXX XXX
BBBBBBBB
