BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Nombre') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'País') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Tipo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de usuarios') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Riesgos (N2)') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Controles') XXXXX
          XXXX XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Evaluadores de Riesgo (RI)') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Evaluadores de Riesgo (RR)') XXXXX XXX
        XXXXX
      XXXXXXXX
      XXXXXXX
          BBB BBBBBBB BB BBBBBBBBB
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                  XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                XXXXXXX
              BBBBB
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BB BBB BBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                  BBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX  XXXXXXXXXXXXXXX
                    XXXX
                  BBBBB
                BBBBBB
              XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BB BBB BBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                  BBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBB BB BBBBBBBBBBBBBBBBB  XXBB BBB BBBBBBBBBBBBXXXXXXBBBBBBBBBBBXXXXXXXXXXXXX
                    XXXX
                  BBBBB
                BBBBBB
              XXXXX XXX
          XXXXX
          BBBBBB
      XXXXXXXX
    XXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Nuevo') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
       gettext(u'Importar') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
