BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Riesgos (N2) que aplican a la compañía') XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXX
                BBB BBBB BBBBBBBBBBB BB BBBBBBBBB
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX
                      XXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXX
                      XXXX
                        XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'REF') XXXXX
                        XXX XXXXXXXXXXXX gettext(u'Nombre') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Descripción') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Principales elementos') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Principales eventos') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Actividad afectada') XXXXX
                        XXX XXXXXXXXXXX gettext(u'Personal expuesto') XXXXX

                        XXXX gettext(u'Riesgo Maestro (N1)') XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Controles') XXXXX
                      XXXXX
                    XXXXXXXX
                    XXXXXXX
                      BBB BB BB BBBBBBBBBBBBBBBBB
                        XXXX
                          XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                      BBBBBB
                    XXXXXXXX
                  XXXXXXXX
                  BBBBBB
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
