BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
              XXXXXXXX gettext(u'Instrucciones') XXXXXXXXX
              XXXX
                XXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Descarga la plantilla de importación') XXXXXXXXXXXXXXXXXX
                XXXX gettext(u'Rellenar la plantilla de importación sin modificar el orden de las columnas') XXXXX
                XXXX gettext(u'Adjuntar el archivo') XXXXX
                XXXX gettext(u'Comprobar los posibles mensajes de error') XXXXX
                XXXX gettext(u'Si no hay errores se le comunicará el resultado de la importación') XXXXX
              XXXXX
              FFFFFFFFFFFFFFF
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Importar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
