BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Respuestas de la evaluación del control') XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX XXXXX X XXXXXXXXXX XXXXXXX gettext(u'RESULTADO ACTUAL:&emsp;') XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBB B B
      BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBB BBBBBBBBBBBB
        BBBBB
      BBBBBB
    BBBB
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'Todavía no hay respuestas para este test de control') 
      XXXX
    BBBBB
  XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B

  XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Plan de Remediación') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
      BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBB
      BBBBBB
    BBBBB
  XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB