BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
    BB BBBBBBBBBBBBB BB BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
      XXX
    BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
      XXX
    BBBBB
  XXX
XXXXXXXXX
XXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
        XX XXX XXX XXXXXXXX XXXXX
        XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XX XXXXXXXXXXXXXX XX XX XX XXXXXXXXXX XX XXXX X
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XXX

    XX XXXXXXXXXX XXX XXXXXXXXX XXX XXXXXX XX XXXXXXXX XX XXX XXXXXXXX XXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X X gettext(u'Descargar') XX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX X XXXXXXXXX
      X
    X

    XX XXXXXXXX X XXX XXXXXXXXXXXXX XX XXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Respuesta incompleta') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Quedan campos pendientes de completar. Por favor, revise su respuesta') 
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX

  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Editar respuesta') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
            BB BBBBB BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            BBBBB
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXX
            XXXXXXXX gettext(u'Comentario') XXXXXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
      XXXXXXX
      XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
    XXXXXX
  XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
