# Generated by Django 4.1 on 2022-11-30 05:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('vat', models.CharField(blank=True, error_messages={'unique': 'Dicho Vat ya está en uso.'}, max_length=20, null=True, unique=True, verbose_name='CIF')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dirección')),
                ('state', models.CharField(blank=True, max_length=140, null=True, verbose_name='Población')),
                ('cp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('type_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo')),
                ('companies_in_scope', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Companies in scope')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañía',
                'ordering': ['ref', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDomainRiskEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Evaluador de Dominio de Riesgo para Compañía',
                'verbose_name_plural': 'Evaluadores de Dominios de Riesgo para Compañías',
                'ordering': ['company', 'domain_risk'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDomainRiskExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Experto de Dominio de Riesgo para Compañía',
                'verbose_name_plural': 'Expertos de Dominios de Riesgo para Compañías',
                'ordering': ['company', 'domain_risk'],
            },
        ),
    ]
