# Generated by Django 4.1 on 2022-08-19 11:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('vat', models.CharField(blank=True, error_messages={'unique': 'Dicho Vat ya está en uso.'}, max_length=20, null=True, unique=True, verbose_name='CIF')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dirección')),
                ('state', models.CharField(blank=True, max_length=140, null=True, verbose_name='Población')),
                ('cp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Sociedad',
                'verbose_name_plural': 'Sociedades',
                'ordering': ['name'],
            },
        ),
    ]
