# Generated by Django 4.1 on 2022-11-30 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companydomainriskexperts',
            name='domain_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.domainrisk'),
        ),
        migrations.AddField(
            model_name='companydomainriskexperts',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Experto asignado'),
        ),
        migrations.AddField(
            model_name='companydomainriskevaluator',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_risk_evaluators', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companydomainriskevaluator',
            name='domain_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.domainrisk'),
        ),
        migrations.AddField(
            model_name='companydomainriskevaluator',
            name='evaluator',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores'),
        ),
        migrations.AddField(
            model_name='company',
            name='evaluators',
            field=models.ManyToManyField(blank=True, related_name='quuestionnaires_evaluators', to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores de Cuestionarios'),
        ),
    ]
