# Generated by Django 4.1.3 on 2023-03-14 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_companycontrols'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontrols',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='companycontrols',
            name='control_test_owners',
            field=models.ManyToManyField(blank=True, related_name='company_controls_owners', to=settings.AUTH_USER_MODEL, verbose_name='Cumplimentadores del Control (Control Owner)'),
        ),
        migrations.AlterField(
            model_name='companycontrols',
            name='control_test_supervisors',
            field=models.ManyToManyField(blank=True, related_name='company_controls_supervisors', to=settings.AUTH_USER_MODEL, verbose_name='Supervisores del Control (Control Supervisor)'),
        ),
    ]
