# Generated by Django 4.1 on 2022-11-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='companies', to='controls.control', verbose_name='Controles asociados'),
        ),
    ]
