# Generated by Django 4.1.3 on 2023-03-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companycontrols_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='controls',
        ),
    ]
