# Generated by Django 4.1 on 2022-10-06 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risks', '0023_alter_riskcompany_description'),
        ('companies', '0003_alter_companydomainriskexperts_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDomainRiskEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('domain_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.domainrisk')),
                ('evaluator', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores')),
            ],
            options={
                'verbose_name': 'Evaluador de Dominio de Riesgo para Compañía',
                'verbose_name_plural': 'Evaluadores de Dominios de Riesgo para Compañías',
                'ordering': ['company', 'domain_risk'],
            },
        ),
    ]
