# Generated by Django 4.1.3 on 2023-03-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontrols',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_controls', to='companies.company'),
        ),
    ]
