# Generated by Django 4.1 on 2022-10-06 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_companydomainriskevaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydomainriskevaluator',
            name='evaluator',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores'),
        ),
    ]
