# Generated by Django 4.1.3 on 2025-03-20 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risks', '0003_alter_riskcompany_name'),
        ('companies', '0005_alter_companycontrols_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRiskExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Experto asignado')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk')),
            ],
            options={
                'verbose_name': 'Experto de Riesgo para Compañía',
                'verbose_name_plural': 'Expertos de Riesgo para Compañías',
                'ordering': ['company', 'risk'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRiskEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_evaluators', to='companies.company')),
                ('evaluator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk')),
            ],
            options={
                'verbose_name': 'Evaluador de Riesgo para Compañía',
                'verbose_name_plural': 'Evaluadores de Riesgo para Compañías',
                'ordering': ['company', 'risk'],
            },
        ),
    ]
