# Generated by Django 4.1 on 2022-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companydomainriskevaluator_evaluator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['ref', 'name'], 'verbose_name': 'Compañía', 'verbose_name_plural': 'Compañía'},
        ),
        migrations.AddField(
            model_name='company',
            name='ref',
            field=models.CharField(max_length=50, null=True, verbose_name='Ref'),
        ),
    ]
