# Generated by Django 4.1.3 on 2025-05-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyriskexperts_companyriskevaluator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['ref', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
