# Generated by Django 4.1 on 2022-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_options_company_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ref',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Ref'),
            preserve_default=False,
        ),
    ]
