# Generated by Django 4.1 on 2022-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Companies in scope'),
        ),
    ]
