# Generated by Django 4.1 on 2022-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_type_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companies_in_scope',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Companies in scope'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo'),
        ),
    ]
