# Generated by Django 4.1 on 2022-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_alter_control_ref'),
        ('companies', '0009_company_companies_in_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='companies', to='controls.control', verbose_name="_('Controles asociados')"),
        ),
    ]
