# Generated by Django 4.1 on 2022-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_alter_control_ref'),
        ('companies', '0010_company_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='companies', to='controls.control', verbose_name='Controles asociados'),
        ),
    ]
