# Generated by Django 4.1 on 2022-10-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydomainriskevaluator',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_risk_evaluators', to='companies.company'),
        ),
    ]
