# Generated by Django 4.1 on 2022-12-06 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_company_evaluators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='evaluators',
            field=models.ManyToManyField(blank=True, related_name='questionnaires_evaluators', to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores de Cuestionarios'),
        ),
    ]
