BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB


XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBXXXXXXX
        XXXXX XXXXXXXXXXXXX gettext(u'Configuración de la aplicación') XXXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Nombre de la aplicación') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Email para notificaciones') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Envío de emails habilitado') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXBB BBBBBBBBBBBBBBBBBBBB gettext(u'Sí') BBBB gettext(u'No') BBBBBXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Habilitar eliminación de archivos en los Tests de Control') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Sí') BBBB gettext(u'No') BBBBBXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Habilitar el módulo de cuestionarios') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Sí') BBBB gettext(u'No') BBBBBXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Obligar a que al crear un control se asocie a un riesgo') XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Sí') BBBB gettext(u'No') BBBBBXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX gettext(u'Modificar') XXXX
      XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX gettext(u'Atrás') XXXX
    XXXXXX

    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
