BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBXXXXXXX
        XXXXX XXXXXXXXXXXXX gettext(u'Configuración de la aplicación') XXXXXXX
      XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXX XXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXX
                FFFFFFFFFFFFFFF
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX gettext(u'Guardar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
