# Generated by Django 4.1 on 2022-12-09 16:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import krm.evaluations.models.control_test_answer
import krm.evaluations.models.remediation_plan
import krm.evaluations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('date_begin', models.DateField(verbose_name='Fecha en la que comenzará el Test de Control')),
                ('status', models.CharField(choices=[('SI', 'Sin iniciar'), ('WO', 'En espera de respuesta del Control Owner'), ('WS', 'En espera de respuesta del Control Supervisor'), ('WA', 'En espera de respuesta del Control Administrator'), ('FI', 'Finalizado')], default='SI', max_length=2, verbose_name='Estado del test de control')),
                ('result', models.CharField(choices=[('EF', 'Efectivo'), ('SE', 'Sin establecer'), ('NE', 'No efectivo')], default='SE', max_length=2, verbose_name='Resultado del test de control')),
                ('remediation_plan_needed', models.BooleanField(default=False, verbose_name='¿Es necesario un plan de remediación?')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tests', to='controls.control')),
                ('control_test_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls_test_owner', to=settings.AUTH_USER_MODEL, verbose_name='Cumplimentador del Test de Control (Control Owner)')),
                ('control_test_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls_test_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor del Test de Control')),
            ],
            options={
                'verbose_name': 'Test de Control',
                'verbose_name_plural': 'Tests de Controles',
            },
        ),
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción del plan de remediación')),
                ('date_end', models.DateField(verbose_name='Fecha de vencimiento del Plan de Remediación')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=krm.evaluations.models.remediation_plan.update_filename, verbose_name='Archivo adjunto')),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('VE', 'Vencido')], default='AC', max_length=2, verbose_name='Estado')),
                ('control_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='evaluations.controltest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remediaton_plans', to=settings.AUTH_USER_MODEL, verbose_name='Creador del Plan de Remediación')),
            ],
            options={
                'verbose_name': 'Plan de remediación',
                'verbose_name_plural': 'Planes de remediación',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('date_begin', models.DateField(verbose_name='Inicio de Evaluación')),
                ('date_intermediate', models.DateField(verbose_name='Fecha límite para Control Owners')),
                ('date_end', models.DateField(verbose_name='Fin de la Evaluación')),
                ('certification_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Año de certificación')),
                ('certification_period', models.CharField(blank=True, max_length=140, null=True, verbose_name='Periodo de certificación')),
                ('status', models.CharField(choices=[('SI', 'Sin iniciar'), ('EP', 'En proceso'), ('FI', 'Finalizado')], default='SI', max_length=2, verbose_name='Estado')),
                ('allow_self_autosupervision', models.BooleanField(default=False, help_text='Si se habilita, el Control Supervisor del test de control puede ser el mismo Control Owner', verbose_name='Permitir auto supervisión de controles')),
                ('admin_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador que ha supervisado la evaluación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evaluación KRC',
                'verbose_name_plural': 'Evaluaciones KRC',
            },
        ),
        migrations.CreateModel(
            name='ControlTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('description', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la realización o supervisión del control')),
                ('attachment_1', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.evaluations.models.control_test_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto 1')),
                ('attachment_2', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.evaluations.models.control_test_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto 2')),
                ('attachment_3', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.evaluations.models.control_test_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto 3')),
                ('control_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.controltest', verbose_name='Test de Control')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_test_answers', to=settings.AUTH_USER_MODEL, verbose_name='Autor de la respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta a un Test de Control',
                'verbose_name_plural': 'Respuestas a un Test de Control',
                'ordering': ('control_test', 'created'),
            },
        ),
        migrations.AddField(
            model_name='controltest',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tests', to='evaluations.evaluation', verbose_name='Evaluación'),
        ),
    ]
