# Generated by Django 4.1.3 on 2024-11-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_controltestanswer_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemediationPlan',
        ),
    ]
