# Generated by Django 4.1 on 2022-09-04 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0010_alter_control_risks_alter_control_sub_processes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0005_evaluation_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('date_begin', models.DateField(verbose_name='Fecha en la que comenzará el Test de Control')),
                ('status', models.CharField(choices=[('SI', 'Sin iniciar'), ('WO', 'En espera de respuesta del Control Owner'), ('WS', 'En espera de respuesta del Control Supervisor'), ('WA', 'En espera de respuesta del Control Administrator'), ('FI', 'Finalizado')], default='SI', max_length=2, verbose_name='Estado del test de control')),
                ('result', models.CharField(choices=[('EF', 'Efectivo'), ('SE', 'Sin establecer'), ('NE', 'No efectivo')], default='SE', max_length=2, verbose_name='Resultado del test de control')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tests', to='controls.control')),
                ('control_test_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls_test_owner', to=settings.AUTH_USER_MODEL, verbose_name='Cumplimentador del Test de Control (Control Owner)')),
                ('control_test_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls_test_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor del Test de Control')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tests', to='evaluations.evaluation', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Test de Control',
                'verbose_name_plural': 'Tests de Controles',
            },
        ),
    ]
