# Generated by Django 4.1 on 2022-09-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import krm.evaluations.models.control_test_answer
import krm.evaluations.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0006_controltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('description', models.TextField(blank=True, help_text='En caso de estar pegando desde el portapapeles asegúrese que ha copiado solo texto. Si el tamaño del texto es mayor a 8000 caracteres considere incluirlo como una evidencia', max_length=10000, null=True, verbose_name='Descripción de la realización o supervisión del control')),
                ('attachment_1', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.evaluations.models.control_test_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto 1')),
                ('attachment_2', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.evaluations.models.control_test_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto 2')),
                ('attachment_3', models.FileField(blank=True, help_text='Tamaño máximo de archivo de 50MB', null=True, upload_to=krm.evaluations.models.control_test_answer.update_filename, validators=[krm.evaluations.validators.validate_file_size], verbose_name='Archivo adjunto 3')),
                ('control_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.controltest', verbose_name='Test de Control')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_test_answers', to=settings.AUTH_USER_MODEL, verbose_name='Autor de la respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta a un Test de Control',
                'verbose_name_plural': 'Respuestas a un Test de Control',
                'ordering': ('control_test', 'created'),
            },
        ),
    ]
