# Generated by Django 4.1 on 2022-09-17 07:27

from django.db import migrations, models
import django.db.models.deletion
import krm.evaluations.models.remediation_plan


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_controltestanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción del plan de remediación')),
                ('date_end', models.DateField(verbose_name='Fecha de vencimiento del Plan de Remediación')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=krm.evaluations.models.remediation_plan.update_filename, verbose_name='Archivo adjunto')),
                ('status', models.CharField(choices=[('AC', 'Activo'), ('VE', 'Vencido')], default='AC', max_length=2, verbose_name='Estado')),
                ('control_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='evaluations.controltest')),
            ],
            options={
                'verbose_name': 'Plan de remediación',
                'verbose_name_plural': 'Planes de remediación',
            },
        ),
    ]
