# Generated by Django 4.1 on 2022-09-17 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0008_remediationplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remediaton_plans', to=settings.AUTH_USER_MODEL, verbose_name='Creador del Plan de Remediación'),
        ),
    ]
