# Generated by Django 4.1 on 2022-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_remediationplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltest',
            name='remediation_plan_needed',
            field=models.BooleanField(default=False, verbose_name='¿Es necesario un plan de remediación?'),
        ),
    ]
