# Generated by Django 4.1 on 2022-09-28 12:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companydomainriskexperts_expert'),
        ('evaluations', '0011_alter_evaluation_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationKrmInherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('date_begin', models.DateField(verbose_name='Inicio de Evaluación')),
                ('date_intermediate', models.DateField(verbose_name='Fecha límite para Control Owners')),
                ('date_end', models.DateField(verbose_name='Fin de la Evaluación')),
                ('certification_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Año de certificación')),
                ('certification_period', models.CharField(blank=True, max_length=140, null=True, verbose_name='Periodo de certificación')),
                ('status', models.CharField(choices=[('SI', 'Sin iniciar'), ('EP', 'En proceso'), ('FI', 'Finalizado')], default='SI', max_length=2, verbose_name='Estado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_inherent_krm', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evaluación Inherente KRM',
                'verbose_name_plural': 'Evaluaciones Inherentes KRM',
            },
        ),
    ]
