# Generated by Django 4.1 on 2022-09-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_evaluationkrminherent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationkrminherent',
            name='date_intermediate',
        ),
    ]
