# Generated by Django 4.1.3 on 2025-03-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_alter_evaluation_certification_year'),
        ('evaluations', '0013_alter_controltestanswer_result'),
    ]

    operations = [
    ]
