# Generated by Django 4.1 on 2022-09-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_remove_evaluationkrminherent_date_intermediate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationKrmInherent',
        ),
    ]
