# Generated by Django 4.1 on 2022-11-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='REF')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, unique=True, verbose_name='Identificador de subproceso')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_processes', to='process.process', verbose_name='Proceso al que pertenece')),
            ],
            options={
                'verbose_name': 'Sub Proceso',
                'verbose_name_plural': 'Sub Procesos',
                'ordering': ['process', 'ref'],
                'unique_together': {('process', 'ref')},
            },
        ),
    ]
