# Generated by Django 4.1 on 2022-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='ref',
            field=models.CharField(max_length=140, unique=True, verbose_name='REF'),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='ref',
            field=models.CharField(max_length=140, unique=True, verbose_name='Identificador de subproceso'),
        ),
    ]
