upstream krm {
  server django:5000;
}

server {
  listen 80;
  server_name   server_name manuscritos.penguinrandomhousegrupoeditorial.com;

  client_max_body_size 100M;

  error_page 404 /404.html;
  location = /404.html {
          root /usr/share/nginx/html;
          internal;
  }
 
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
          root /usr/share/nginx/html;
          internal;
  }

  proxy_intercept_errors on;

  location /media/ {
    alias /krm-media/;
  }

  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    if (!-f $request_filename) {
      proxy_pass http://krm;
      break;
    }
  }
}