BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXX
      XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
          XXXXXXXXX X
            XX XXX XX XXXX XX XXXXXXXX
            XXX XXXXX

            XX XXX XXX XXXXXXX XXXX XX XXXXXX XX XXXXXXX
            XXXXXXXX XXXX
          X
        X
      X
      XXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXXX XX X
      XXX
  
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXX
          XXXXXXXXXXX XXXXXXXX
    XXX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B
  XXXX XXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
         gettext(u'Debe establecerse un plan de remediación, en la parte inferior podrá rellenarlo si es el Control Owner') 
      XXXXXX
    XXXXXX
  XXXXXX
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
XXXX XXXXXXXXXX XXXX XXXXXX
  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
       gettext(u'Puede editar el plan de remediación ya adjunto, en la parte inferior podrá rellenarlo si es el Control Owner') 
    XXXXXX
  XXXXXX
XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Respuestas de la evaluación del control') XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX XXXXX X XXXXXXXXXX XXXXXXX gettext(u'RESULTADO ACTUAL:&emsp;') XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B
      BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBBBB
      BBBBBB
    BBBB
      XX XXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Todavía no hay respuestas para este test de control') 
      XXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXX XXXXXXXXXXXXX gettext(u'PLAN DE REMEDIACIÓN') XXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBB BB BBBB
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Administración del Control') XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
            FFFFFFFFFFFFFFF
            XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Finalizar revisión del control') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
BBBBB

BBBBBBBB BBBBBBB