# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Image registry
image:
  registry: quay.pre.eci.geci

# Recursos asignados al contenedor
container:
  port: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi
  image:
    pullPolicy: Always
  deployment:
    strategy: Rolling
  probes:
    port: 8080
    ready:
      path: /hello
      periodSeconds: 10
      timeoutSeconds: 5
    live:
      path: /hello
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5

# Service svc
service:
  application:
    type: ClusterIP
    sessionAffinity: None
  management:
    type: ClusterIP
    sessionAffinity: None

# Config Maps
configmaps:
  create: false
  values:
    # KEY: 'value'

# Secrets
secrets:
  create: false
  values:
    # KEY: 'value'

# Listado de volumenes a montar en el contenedor
volumes:
  create: false
  list:
    #- volumeName: resources-volume
    #  claimName: resources-claim
    #  accessModes:
    #    - ReadOnlyMany
    #  mounts:
    #  - mountPath: /var/ssl/private/client.keystore.jks
    #    subPath: kafkacorp/uat/client.keystore.jks