# Generated by Django 4.1 on 2022-08-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Dominio de Riesgo',
                'verbose_name_plural': 'Dominios de Riesgo',
                'ordering': ['ref', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción')),
                ('domain_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.domainrisk', verbose_name='Dominio de Riesgo')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'ordering': ['domain_risk', 'name'],
            },
        ),
    ]
