# Generated by Django 4.1 on 2022-12-09 16:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Dominio de Riesgo',
                'verbose_name_plural': 'Dominios de Riesgo',
                'ordering': ['ref', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='REF')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(max_length=10000, verbose_name='Descripción')),
                ('domain_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.domainrisk', verbose_name='Dominio de Riesgo')),
            ],
            options={
                'verbose_name': 'Riesgo Maestro',
                'verbose_name_plural': 'Riesgos Maestros',
                'ordering': ['domain_risk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='REF')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('impact_inherent', models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Impacto inherente')),
                ('probability_inherent', models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Probabilidad inherente')),
                ('impact_residual', models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Impacto residual')),
                ('probability_residual', models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Probabilidad residual')),
                ('krm_activity_affected', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Actividad afectada')),
                ('krm_main_events', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Describa los principales eventos en los que el riesgo se materializa o se espera que se materialice. Comentarios')),
                ('krm_exposed_staff', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Personal especialmente expuesto al Riesgo')),
                ('krm_main_elements', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Principales elementos del Riesgo')),
                ('risk_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.riskmaster', verbose_name='Riesgo Maestro')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'ordering': ['risk_master', 'name'],
            },
        ),
    ]
