# Generated by Django 4.1 on 2022-12-09 16:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('krm_activity_affected', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Actividad afectada')),
                ('krm_main_events', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Describa los principales eventos en los que el riesgo se materializa o se espera que se materialice. Comentarios')),
                ('krm_exposed_staff', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Personal especialmente expuesto al Riesgo')),
                ('krm_main_elements', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Principales elementos del Riesgo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krm_risks', to='companies.company', verbose_name='Compañía')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks_company', to='risks.risk', verbose_name='Riesgo original')),
            ],
            options={
                'verbose_name': 'Riesgo-Compañía',
                'verbose_name_plural': 'Riesgos-Compañías',
                'ordering': ['risk', 'company'],
            },
        ),
    ]
