# Generated by Django 4.1 on 2022-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Risk',
            new_name='RiskMaster',
        ),
        migrations.AlterModelOptions(
            name='riskmaster',
            options={'ordering': ['domain_risk', 'name'], 'verbose_name': 'Riesgo maestro', 'verbose_name_plural': 'Riesgos maestros'},
        ),
    ]
