# Generated by Django 4.1 on 2022-08-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_rename_risk_riskmaster_alter_riskmaster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskmaster',
            options={'ordering': ['domain_risk', 'name'], 'verbose_name': 'Riesgo Maestro', 'verbose_name_plural': 'Riesgos Maestros'},
        ),
    ]
