# Generated by Django 4.1 on 2022-12-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_riskcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
    ]
