# Generated by Django 4.1.3 on 2025-03-24 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risks', '0003_alter_riskcompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcompany',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_risks', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador asignado'),
        ),
        migrations.AddField(
            model_name='riskcompany',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_risks', to=settings.AUTH_USER_MODEL, verbose_name='Experto asignado'),
        ),
    ]
