# Generated by Django 4.1.3 on 2025-03-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_alter_riskcompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='event_speed',
            field=models.PositiveIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Velocidad de ocurrencia'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_inherent',
            field=models.PositiveIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Impacto inherente'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact_residual',
            field=models.PositiveIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=0, verbose_name='Impacto residual'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability_inherent',
            field=models.PositiveIntegerField(choices=[(1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=3, verbose_name='Probabilidad inherente'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability_residual',
            field=models.PositiveIntegerField(choices=[(1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=0, verbose_name='Probabilidad residual'),
        ),
    ]
