# Generated by Django 4.1.3 on 2025-03-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_risk_event_speed_alter_risk_impact_inherent_and_more'),
        ('risks', '0004_riskcompany_evaluator_riskcompany_expert'),
    ]

    operations = [
    ]
