# Generated by Django 4.1 on 2022-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='impact_inherent',
            field=models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Impacto inherente'),
        ),
        migrations.AddField(
            model_name='risk',
            name='impact_residual',
            field=models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Impacto residual'),
        ),
        migrations.AddField(
            model_name='risk',
            name='probability_inherent',
            field=models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Probabilidad inherente'),
        ),
        migrations.AddField(
            model_name='risk',
            name='probability_residual',
            field=models.PositiveIntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], default=3, verbose_name='Probabilidad residual'),
        ),
    ]
