# Generated by Django 4.1.3 on 2025-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_merge_20250328_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='event_speed',
            field=models.PositiveIntegerField(choices=[(0, 'Sin establecer'), (1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], default=0, verbose_name='Velocidad de ocurrencia'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability_residual',
            field=models.PositiveIntegerField(choices=[(1, 'Remoto'), (2, 'Posible'), (3, 'Probable'), (4, 'Muy probable'), (5, 'Prácticamente cierto')], default=3, verbose_name='Probabilidad residual'),
        ),
    ]
