# Generated by Django 4.1 on 2022-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_risk_impact_inherent_risk_impact_residual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainrisk',
            name='ref',
            field=models.CharField(default=5, max_length=50, verbose_name='Ref'),
            preserve_default=False,
        ),
    ]
