# Generated by Django 4.1.3 on 2025-04-02 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risks', '0006_alter_risk_event_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_risks', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador asignado'),
        ),
    ]
