# Generated by Django 4.1 on 2022-08-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_alter_domainrisk_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['domain_risk', 'name'],
                     'verbose_name': 'Riesgo', 'verbose_name_plural': 'Riesgos'},
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_master',
        ),
        migrations.AddField(
            model_name='risk',
            name='domain_risk',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='risks', to='risks.domainrisk', verbose_name='Dominio de Riesgo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risk',
            name='ref',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='REF'),
        ),
        migrations.DeleteModel(
            name='RiskMaster',
        ),
    ]
