# Generated by Django 4.1.3 on 2025-04-23 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risks', '0007_alter_riskcompany_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_risks', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador de riesgo residual asignado'),
        ),
        migrations.AlterField(
            model_name='riskcompany',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_risks', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador de riesgo inherente asignado'),
        ),
        migrations.AlterField(
            model_name='riskcompany',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre'),
        ),
    ]
