# Generated by Django 4.1 on 2022-09-16 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0007_alter_risk_options_remove_risk_risk_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='REF'),
            preserve_default=False,
        ),
    ]
