# Generated by Django 4.1 on 2022-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0008_alter_risk_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainrisk',
            name='ref',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ref'),
        ),
    ]
