# Generated by Django 4.1 on 2022-09-22 10:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0009_alter_domainrisk_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name='Descripción'),
        ),
    ]
