# Generated by Django 4.1 on 2022-09-22 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0010_alter_risk_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='krm_activity_affected',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Actividad afectada'),
        ),
        migrations.AddField(
            model_name='risk',
            name='krm_exposed_staff',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Personal especialmente expuesto al Riesgo'),
        ),
        migrations.AddField(
            model_name='risk',
            name='krm_main_elements',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Principales elementos del Riesgo'),
        ),
        migrations.AddField(
            model_name='risk',
            name='krm_main_events',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Describa los principales eventos en los que el riesgo se materializa o se espera que se materialice. Comentarios'),
        ),
    ]
