# Generated by Django 4.1 on 2022-09-22 18:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0011_risk_krm_activity_affected_risk_krm_exposed_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['risk_master', 'name'], 'verbose_name': 'Riesgo', 'verbose_name_plural': 'Riesgos'},
        ),
        migrations.RemoveField(
            model_name='risk',
            name='domain_risk',
        ),
        migrations.CreateModel(
            name='RiskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='REF')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(max_length=10000, verbose_name='Descripción')),
                ('domain_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.domainrisk', verbose_name='Dominio de Riesgo')),
            ],
            options={
                'verbose_name': 'Riesgo Maestro',
                'verbose_name_plural': 'Riesgos Maestros',
                'ordering': ['domain_risk', 'name'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.riskmaster', verbose_name='Riesgo Maestro'),
        ),
    ]
