# Generated by Django 4.1 on 2022-09-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0012_alter_risk_options_remove_risk_domain_risk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.riskmaster', verbose_name='Riesgo Maestro'),
            preserve_default=False,
        ),
    ]
