# Generated by Django 4.1 on 2022-09-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0014_riskcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskcompany',
            options={'ordering': ['risk', 'company'], 'verbose_name': 'Riesgo-Compañía', 'verbose_name_plural': 'Riesgos-Compañías'},
        ),
    ]
