# Generated by Django 4.1 on 2022-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0015_alter_riskcompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcompany',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
