# Generated by Django 4.1 on 2022-09-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companydomainriskexperts_expert'),
        ('risks', '0016_riskcompany_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='companies.company', verbose_name='Compañía'),
        ),
    ]
