# Generated by Django 4.1 on 2022-09-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0018_alter_riskcompany_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks_company', to='risks.risk', verbose_name='Riesgo original'),
        ),
    ]
