# Generated by Django 4.1 on 2022-09-27 11:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0020_alter_risk_krm_activity_affected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='krm_activity_affected',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Actividad afectada'),
        ),
        migrations.AlterField(
            model_name='riskcompany',
            name='krm_exposed_staff',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Personal especialmente expuesto al Riesgo'),
        ),
        migrations.AlterField(
            model_name='riskcompany',
            name='krm_main_elements',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Principales elementos del Riesgo'),
        ),
        migrations.AlterField(
            model_name='riskcompany',
            name='krm_main_events',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Describa los principales eventos en los que el riesgo se materializa o se espera que se materialice. Comentarios'),
        ),
    ]
