# Generated by Django 4.1 on 2022-09-27 15:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0021_alter_riskcompany_krm_activity_affected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
    ]
