# Generated by Django 4.1 on 2022-09-27 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0022_alter_risk_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcompany',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
    ]
