BBBB BBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
      XXX XXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Evaluación') X XXXXXXXXXXXXX gettext(u'Evaluación') XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Control') X XXXXXXXXXXXXX gettext(u'Control') XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Fecha de inicio') X XXXXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Supervisor') X XXXXXXXXXXXXX gettext(u'Supervisor') XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Responsable') X XXXXXXXXXXXXX gettext(u'Responsable') XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Estado') X XXXXXXXXXXXXX gettext(u'Estado') XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Resultado') X XXXXXXXXXXXXX gettext(u'Resultado') XXXXXXX
      XXXXX
    XXXXXXXX
    XXXXXXX
    BBB B BB BBBBBBBBBBB
      BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
      BBBBBB
    BBBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX
