BBBB BBBB


XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Datos de la evaluación') 
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXX X XXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sociedades en alcance') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              BBBBBB
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
              BBBBB
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Año de certificación') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Periodo de certificación') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha límite para Control Owners') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de fin') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXX
XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Datos generales del control') 
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia del Control') XXXXXXXXXXXXX
              XXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Alcance') XXXXXXXXXXXXX
              BBBBB
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                BBBB
                  XX XXXXXXXXX
                BBBBB
                  XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                  XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  BBBBB
                XXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Número de riesgos mitigados por el Control') XXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          BB BBBBB BB BBBBBBBBBBB
          XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Subprocesos del control') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBBBBB
              BBBB
                XXX gettext(u'Sin subprocesos asociados') XXXX
              BBBBB
            XXXXXX
          XXXXXX
          BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Control owner') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Control supervisor') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Riesgos asociados al control') 
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
              XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Riesgo') XXXXX
                  XXX XXXXXXXXXXXX gettext(u'Nombre') XXXXX
                  XXX XXXXXXXXXXX gettext(u'Descripción') XXXXX
                  XXX XXXXXXXXXXX gettext(u'Principales elementos') XXXXX
                  XXX XXXXXXXXXXX gettext(u'Principales eventos') XXXXX
                  XXX XXXXXXXXXXX gettext(u'Actividad afectada') XXXXX
                  XXX XXXXXXXXXXX gettext(u'Personal expuesto') XXXXX
                  XXXX gettext(u'Dominio de Riesgo') XXXXX
                  XXXX gettext(u'Riesgo Maestro (N1)') XXXXX
                XXXXX
              XXXXXXXX
              XXXXXXX
              BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBB
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                  BBBB
                  XX XXXXXXXXX
                  BBBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBBB
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
                  BBBB
                  XX XXXXXXXXX
                  BBBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXX
                XXXXX
              XXXXX
              BBBBBB
              XXXXXXXX
            XXXXXXXX
          XXXXXX
          BBBB
            XXX gettext(u'Sin riesgos asociados') XXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXX
XXXXXX
XXXXXX

BB BBBBB BB BBBBBBBBBBB

XXXX XXXXXXXXXX XXXX XXXXXX
  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Por favor, deberá subir las evidencias indicadas en "Evidencia" al sitio de WorkSpace ')  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXX  gettext(u'(Ruta: Documentos > 2022 > Sociedad > Área)') 
    XXXXXX
  XXXXXX
XXXXXX

BBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Datos del control') 
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo de control') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Frecuencia') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Key control') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXX _("Si, No") XXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          BB BBBBB BB BBBBBBB
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'ELC') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXX _("Si, No") XXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          BBBBB
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Automatización') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          BB BBBBB BB BBBBBBB
          BB BBBBBBBBBBBBBBB BB BBBB
          XXXX XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sistemas') XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXX
          XXXXXX
          BBBBB
          BBBBB
        XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        BB BBBBBBBBBBBB
        BB BBBBB BB BBBBBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Nombre') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
        XXXXXX
        BBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Objetivo') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
        XXXXXX
        BBBBB
        BBBBB
        BB BBBBBBBBBBBBBBBBBBB BB BBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
        XXXXXX
        BBBBB
        BB BBBBB BB BBBBBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Plan de testeo') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Evidencia') XXXXXXXXXXXXX
          XXXXXFFFFXXXXXX
        XXXXXX
        BBBBB
      XXXXXX
      XXXXXXX
        XXXXXXX
          BB BBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'GAP') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Existencia') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Integridad') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Valoración') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Obligacion') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Presentación') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Precisión') XXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBB BB BBB
          XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fraude') XXXXXXXXXXXXXXXXXX
          BBBBB
        XXXXXXXX
        XXXXXXX
          XXXX
          BB BBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBB BB BBB
          XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
        XXXXXXXX
    XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXX
XXXXXX
