BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Estado') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'REF') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Auto supervisión') X XXXXXXX _("Si,No") XXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Compañía') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Año de certificación') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Periodo de certificación') X XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Fecha de inicio') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Fecha límite para control owner') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Fecha final') X XXXXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Importar plantilla de asignación de Controles para el Test de Proceso') X 
        XXXXX
        XXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
          XXXXXX
          XXXXXXX  XXXXXXXXXX XXXXXXXXXXX XXXXXXXX gettext(u'Subir plantilla de asignación de controles') XXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB