BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 

BBBBB BBBBBBBBB

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXX
  XXXXXX X
    XXXXXX XXXXX XXXXXXXXXXX
    XXXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXX XX
    XXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X
XXXXXXXX
XXXXXXXX

  XXXXXXXX XXXXXXXXXXXX XXXX X
    XXXXXXXXX X XXX
    XXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXX XXX X

      XXX XXX X X XX XXX XX XXX XXXXX XX X
      XXX XXX X X XX XXX XX XXX XXXXX XX X

      XX XXXXXXXXX X XX X
        XXXXX X XXXXXXXXXX
        XXXXX X X
        XXXXXXXX X XXXXXXXXXXX

        XXXXX X XXXXXXXXXX
        XXXXX X X
        XXXXXXXX X XXXXXXXXXXX

      X XXXX X
        XXXXX X XXXXXXXXXX
        XXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX X XXXXXXXXXXX

        XXXXX X XXXXXXXXXX
        XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX X XXXXXXXXXXX
      X
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
    XXX

    XXX XXXXXXX X X
      XXXXXXX X
        X
          XXXXX XXXXXXXXXX
          XXXXX XXXXXXXXX
        XX
        X
          XXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXX
        X
      XX
      XXXXXX X
        XXXXXXX XXXX
        XXXXX XXXXXX
        XXXXXXXX XXXXX
        XXXXXXXX X
          XXXXX XXXXXX
        X
      XX
      XXXXXXXXXXXX X
        XXXX X
          XXXXXXXXXXXXX XXX
          XXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX XX XXXX XXXXXXX XXXXXX
          XX
        X
      XX

      XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXX XXXXX X
          XXXXXX XXXX
        XX
        XXXXXX X
          XXXXXXXXX XXXXXXX
          XXXXXXX XXXXXXXXXXX
        X
      XX
      XXXXXXXX X
        XXXXXXX XXXXXXXX XX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX X XX X
          XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX X
            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX X
            XXXXX X XXXXXX X XXXXXX X
            XXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX X
            XXXXXXXXX X
            XXXXXXXX X
            XXXXXX X
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXX X X XXXXXXXXXXX XXXXXX X X XXXXXXXXXXX X XX XXXXXXX XXXXX XXXXXX XXXXX XXXXX XXXX XXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXX XXXXXXX XXX XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X X XXXXXXXXXXXXXXXXX X XXXXXXXXX X
            XXXXXXXX
            X XXXXXXXXX
        XX
      XX
      XXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX X
          XXXXX XXXXX
        XX
        XXXXXXXXXX X
          XXXXX XXXXX
        XX
        XXXXXXXXXXX X
          XXXXXXXX XXXXXX
        XX
        XXXXXXXX X
          XXXXXXXX XXXXXX
        X
      XX
      XXXXXX X
        XXXXXXXXXXX X
          XXXXX XXXXX
        XX
        XXXXXXXXXX X
          XXXXX XXXXXX
        XX
        XXXXXXX X
          XXXXX XXXXXX
          XXXXXXXXXX XXXXXXXX XXXXX X
            XXXXXX XXXX
          X
        X

      XX
    XX

    XXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX X XXXXXXXXXXXX XXXX X XXXXXXXXXXXX XXXX X XXXXXXXXXXXX XXXX X XXXXXXXXXXXX XXXX X XXXXXXXXXXXX X
    XXX XXXXX
    XXX XXXXXX

    XX XXXXX XXXXXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX X X
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX X
          X
            XXXXXX XXX
            XXXXX XXXXXX XXXXX XXXXX XXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
          X
        X
      XX

    X XXXX XX XXX XX XXXXXXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX X X
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX X
          X
            XXXXXX XXX
            XXXXX XXXXXX XXXXX XXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
          X
        X
      XX
    X

    XXXXX XXXXXX X X
      XXXXX XXXXXX
      XXXXX XXXXX
      XXXXX X
        XXXXX XXXXXXXXXXX
      XX
      XXXXXXXX X
        XXXXXXXXXX X
          XXXXXXXXX XXXXX
        XX
        XXXXXXXXXXX XXXXX
        XXXXXXXX X
          XXXXXXX X
            XXXXXXXX XXXXXX
          XX
          XXXXXX X
            XXXXXXXX XXXXX
            XXXXX XXXXXX
            XXXXX X
              XXXXX XXX
              XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX
            XX
          XX

        XX
      XX
    XX
    XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXX
  X

XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Referencia') XXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Compañía') XXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
                  XXXXXXX
                XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Tipo') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Sociedades en alcance') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBB
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado') XXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB BB BBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX
              BBBB BBBBBBBBBBBBBBBBB BB BBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX
              BBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX
              BBBBB
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX
              BBBBBB
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Supervisor que ha validado') XXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') XXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Año de certificación') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Periodo de certificación') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de inicio') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha límite Control Owners') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de fin') XXXXXXXXXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXX
          XXX XXXXXXXXXXXXX XXX
          XXXXX XXXXX XXX
          XX XXXXX XX XXXXX X
            XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
          X XXXX XX XXXXX XX XXXXX X
            XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
          X
          XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXX XXX XXX XXXX
        XXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Sin empezar') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Control Owner') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Control Supervisor') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Administrador') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Finalizado') XXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXX XXX XXX XXXX
        XXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'No empezado') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Efectivo') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Efectivo con recomendación') XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'No efectivo') XXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'N/A') XXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Editar') XXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Eliminar') XXXX XXX
    BB BBBBBBBBBBBBBBBBB BB BBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Lanzar controles') XXXXXXXXX
    XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Descargar Evaluación') XXXXXXXXX
    XXXXXXX
    XXXXXX
    BBBB
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX gettext(u'Debe asignar todos los controles para lanzar la evaluación') XXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Lanzar controles') 
    XXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Descargar plantilla de asignación') XXXXXXXXX
    XXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
      XXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXX gettext(u'Subir plantilla de asignación de controles') XXXX
    BBBBB
    BBBB BBBBBBBBBBBBBBBBB BB BBBB
    XXXX XXXXXXXXXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX gettext(u'Finalizar evaluación') XXXXXXXXX
    XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX  XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Notificaciones') XXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Descargar Evaluación') XXXXXXXXX
    XXXXXXX
    XXXXXX
    BBBB BBBBBBBBBBBBBBBBB BB BBBB
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Descargar Evaluación') XXXXXXXXX
    XXXXXXX
    BBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Atrás') XXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Controles de la Evaluación') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXXX
          XXXXXXXXX
          XXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Evidencia') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Número de riesgos') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Control Owner/Supervisor') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Efectividad') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBB BBBBBBBBB BB BBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            BBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBXXXXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFFFFFFFF
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX
              BBBBBB
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XX X XXXXXXXXXXXXXXX XXXXXXX
                XXXX
              BBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXXXXXXXX gettext(u'CO: Asignar') XXXXXXXXXXXXXXX
              BBBBB
              BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XX X XXXXXXXXXXXXXXX XXXXXXX
                XXXX
              BBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXXXXXXXX gettext(u'CS: Asignar') XXXXXXXXXXXXXXX
              BBBBB
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBB BB BBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
              BBBB BBBBBBBBB BB BBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
              BBBB BBBBBBBBB BB BBBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
              BBBB BBBBBBBBB BB BBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
              BBBB BBBBBBBBB BB BBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen tests de control para esta Evaluación') X
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Volver') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB
