BBBBBBB BBBBBB

BBBB BBBB
 gettext(u'Sin asignar') 
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXXXXXX X XX X XX X XXXXXXXX
      XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
      XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
      XXXXXXXXXXX XXXXX
    XXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXX XXXX XXXXXXXX X XX X XX X XXXXXXXX
      XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
      XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
      XXXXXXXXXXX XXXXX
    XXX
  XXX

  XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX

    XX XXXXXXXXXXXX XX XXXXX X
      XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
    X XXXX X
      X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX
    X
  X
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXX XXXX XXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX
      XX
  X
  XXXXXXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXX XXXX XXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX

      XX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXX XXXX XXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX
      XX
  X
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXX XXXX XXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX

      XX
  X
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB


XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Enviar recordatorio') XXXXX
            XXXX gettext(u'Usuario') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Controles completados') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Controles pendientes de completar') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Notificación') XXXXX
          XXXXX
        XXXXXXXX
        XXXXXXX
          BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBB B B
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              BBBB
                 gettext(u'No hay tareas pendientes') 
              BBBBB
            XXXXX
            XXXX
              
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX
              BBB BBBBB BB BBBBBBBBBBBBBBBB
              XXXX
                  XFFFFFFFFF FFFFFFXXXXXBB BBB BBBBBBBBBBBBXXXXBBBBB
              XXXXX
              BBBBBB
            XXXXX
          XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX

      BB BBBBBBBBBBBBBBBBB BB BBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Notificar usuarios (COwner)') 
            XXXXXXXXX
          XXXXXX
        XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Envío de notificaciones') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'¿Desea enviar una notificación de recordatorio de tareas pendientes a los siguientes usuarios?') 
        XXXXX
          XXXX
          XXX XX XXXXXXXXXXXXXXX
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Enviar notificaciones') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX

XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Enviar recordatorio') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Usuario') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Controles supervisados') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Controles pendientes de supervisar') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Notificación') XXXXX
          XXXXX
        XXXXXXXX
        XXXXXXX
          BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBB B B
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              BBBB
                 gettext(u'No hay tareas pendientes') 
              BBBBB
            XXXXX
            XXXX
              
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX
              BBB BBBBB BB BBBBBBBBBBBBBBBB
              XXXX
                  XFFFFFFFFF FFFFFFXXXXXBB BBB BBBBBBBBBBBBXXXXBBBBB
              XXXXX
              BBBBBB
            XXXXX
          XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX

      BB BBBBBBBBBBBBBBBBB BB BBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Notificar usuarios (CSupervisor)') 
            XXXXXXXXX
          XXXXXX
        XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXX XXXXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Envío de notificaciones') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'¿Desea enviar una notificación de recordatorio de tareas pendientes a los siguientes usuarios?') 
        XXXXX
          XXXX
          XXX XX XXXXXXXXXXXXXXX
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Enviar notificaciones') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX

BBBBBBBB BBBBBBB
