BBBBBBB BBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXXXXXXXXXXXXXXXX
    XXX
XX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
  XXXXXX X
    XXXXXX XXXX XXXXXXXXXXX
    XXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXX XX
    XXXXXXX XXXXX
  X

  XXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X
XXXXXXXX
XXXXXXXX
  XXX XXXXXXXXXXXXX XXX
  XXXXX XXXXX XXX
  XX XXXXX XX XXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
  X XXXX XX XXXXX XX XXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
  X

  XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXX X

    XXXXX XXXX X X
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX X
        X
          XXXXXX XXX
          XXXXX XXXXXX XXXXX XXXXX XXXXX XXXXXX
          XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
        X
      X
    XX
    XXXXX XXXXXX X X
      XXXXX XXXXXX
      XXXXX XXXXX
      XXXXX X
        XXXXX XXXXXXXXXXX
      XX
      XXXXXXXX X
        XXXXXXXXXX X
          XXXXXXXXX XXXXX
        XX
        XXXXXXXXXXX XXXXX
        XXXXXXXX X
          XXXXXXX X
            XXXXXXXX XXXXXX
          XX
          XXXXXX X
            XXXXXXXX XXXXXX
          XX
          XXXXXXXX X
            XXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXX X
              XXXXXX XXXXXXXX XXXXXXXXXXXXX X
                XXXXXX XXXXXXXXXXXXXXXXXXX
              X
            XX
          XX
        XX
      XX
    XX
    XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXX
  X
XXXXXXXXX

XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Filtrado de evaluaciones') XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXX
        FFFFFFFFFFFFFFF
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXX
        FFFFFFFFFFFFFFF
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'en progreso') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX

  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Controles') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX
                XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXFFFFFFFFFFFFXXXXXX
            XXXXXFFFFFFFFFFFFXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX
            BBBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXX
          XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXX XXX XXX XXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB BB BBBB
            XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBB BBBBBBBBBBBBBBBBB BB BBBB
            XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBB
            XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBBB
          XXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Sin empezar') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Control Owner') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Control Supervisor') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Administrador') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Finalizado') XXXXXXXXXXX
    XXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de controles en proceso') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Nuevo') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'finalizadas') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Acción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'REF') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Periodo evaluado') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Fechas evaluación') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Compañía') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Número de Controles') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Estado') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXX
                XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXFFFFFFFFFFFFXXXXXX
            XXXXXFFFFFFFFFFFFXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX
            BBBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXX
          XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXX XXX XXX XXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB BB BBBB
            XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBB BBBBBBBBBBBBBBBBB BB BBBB
            XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBB
            XX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBBB
          XXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Sin empezar') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Control Owner') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Control Supervisor') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'En espera del Administrador') XXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Finalizado') XXXXXXXXXX
    XXXXXX
    BBBB
    XXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'No existen evaluaciones de controles finalizadas') XXXXXXX
      XXXXXX
    XXXXXX
    BBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'Nuevo') XXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
