# Generated by Django 4.1 on 2022-08-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risks', '0006_alter_domainrisk_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('ref', models.CharField(max_length=140, verbose_name='Identificador de Control')),
                ('objective', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Objetivo del Control')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción del Control')),
                ('action_plan', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Plan de Acción')),
                ('testing_procedure', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Procedimiento de testeo')),
                ('key_control', models.BooleanField(default=False, verbose_name='¿Es un key control?')),
                ('control_type', models.CharField(choices=[('P', 'Preventivo'), ('D', 'Detectivo')], max_length=2, verbose_name='Tipo de control')),
                ('automation', models.CharField(choices=[('M', 'Manual'), ('A', 'Automático'), ('S', 'Semiautomático')], max_length=2, verbose_name='Automatización del control')),
                ('systems', models.CharField(blank=True, max_length=140, null=True, verbose_name='Sistemas')),
                ('control_frequency', models.CharField(choices=[('BD', 'Bajo demanda'), ('DI', 'Diario'), ('1W', 'Semanal'), ('2W', 'Quincenal'), ('1M', 'Mensual'), ('3T', 'Trimestral'), ('6M', 'Semestral'), ('1Y', 'Anual')], max_length=2, verbose_name='Frecuencia del control')),
                ('is_gap', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='GAP')),
                ('assert_existence', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Existency')),
                ('assert_completeness', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Completness')),
                ('assert_valuation', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Valuation')),
                ('assert_rights', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Obligation right')),
                ('assert_disclosure', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Presentation')),
                ('assert_accurancy', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Accurancy')),
                ('assert_froud', models.CharField(choices=[('-', 'No aplica'), ('Y', 'Sí'), ('N', 'No')], default='-', max_length=1, verbose_name='Fraud')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='risks.risk', verbose_name='Riesgo asociado')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controles',
                'ordering': ['risk', 'ref'],
                'unique_together': {('risk', 'ref')},
            },
        ),
    ]
