# Generated by Django 4.1 on 2022-08-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='objective',
            new_name='name',
        ),
    ]
