# Generated by Django 4.1.3 on 2023-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_frequency',
            field=models.CharField(choices=[('BD', 'Bajo demanda'), ('CO', 'Constante'), ('DI', 'Diario'), ('1W', 'Semanal'), ('2W', 'Quincenal'), ('1M', 'Mensual'), ('2M', 'Bimensual'), ('3T', 'Trimestral'), ('6M', 'Semestral'), ('1Y', 'Anual'), ('2Y', 'Bienal'), ('3Y', 'Trienal')], max_length=2, verbose_name='Frecuencia del control'),
        ),
    ]
