# Generated by Django 4.1 on 2022-08-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_rename_objective_control_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='action_plan',
        ),
    ]
