# Generated by Django 4.1.3 on 2023-04-04 11:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_alter_control_control_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='evidence',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Evidencia'),
        ),
        migrations.AddField(
            model_name='control',
            name='scope',
            field=models.CharField(blank=True, choices=[('S', 'Sociedad'), ('C', 'Corporativo'), ('G', 'Grupo')], max_length=1, null=True, verbose_name='Alcance'),
        ),
        migrations.AlterField(
            model_name='control',
            name='testing_procedure',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Procedimiento de testeo'),
        ),
    ]
