# Generated by Django 4.1 on 2022-08-19 11:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_control_action_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='name',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Objetivo del Control'),
        ),
    ]
