# Generated by Django 4.1 on 2022-08-19 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_alter_control_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Descripción del Control'),
        ),
        migrations.AlterField(
            model_name='control',
            name='testing_procedure',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Procedimiento de testeo'),
        ),
    ]
