# Generated by Django 4.1.3 on 2024-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_alter_control_control_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='block',
            field=models.BooleanField(default=False, verbose_name='¿Bloqueado?'),
        ),
    ]
