# Generated by Django 4.1.3 on 2024-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_control_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='scope',
            field=models.CharField(blank=True, choices=[('S', 'Sociedad'), ('C', 'Corporativo'), ('G', 'Grupo'), ('D', 'Division'), ('P', 'Planta')], max_length=1, null=True, verbose_name='Alcance'),
        ),
    ]
