# Generated by Django 4.1 on 2022-08-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_alter_control_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['ref'], 'verbose_name': 'Control', 'verbose_name_plural': 'Controles'},
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='control',
            name='risk',
        ),
    ]
