# Generated by Django 4.1 on 2022-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_alter_domainrisk_ref'),
        ('process', '0001_initial'),
        ('controls', '0006_alter_control_options_alter_control_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='risk_masters',
            field=models.ManyToManyField(to='risks.riskmaster', verbose_name='Riesgos asociados'),
        ),
        migrations.AddField(
            model_name='control',
            name='sub_processes',
            field=models.ManyToManyField(to='process.subprocess', verbose_name='SubProcesos asociados'),
        ),
    ]
