# Generated by Django 4.1.3 on 2024-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_alter_control_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_frequency',
            field=models.CharField(choices=[('BD', 'Bajo demanda'), ('CO', 'Constante'), ('DI', 'Diario'), ('1W', 'Semanal'), ('2W', 'Quincenal'), ('1M', 'Mensual'), ('2M', 'Bimensual'), ('3T', 'Trimestral'), ('4T', 'Cuatrimestral'), ('6M', 'Semestral'), ('1Y', 'Anual'), ('2Y', 'Bienal'), ('3Y', 'Trienal'), ('4Y', 'Cuatrienal'), ('5Y', 'Quinquenal')], max_length=2, verbose_name='Frecuencia del control'),
        ),
    ]
