# Generated by Django 4.1 on 2022-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
        ('risks', '0006_alter_domainrisk_ref'),
        ('controls', '0007_control_risk_masters_control_sub_processes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='risk_masters',
            field=models.ManyToManyField(blank=True, to='risks.riskmaster', verbose_name='Riesgos asociados'),
        ),
        migrations.AlterField(
            model_name='control',
            name='sub_processes',
            field=models.ManyToManyField(blank=True, to='process.subprocess', verbose_name='SubProcesos asociados'),
        ),
    ]
