# Generated by Django 4.1 on 2022-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_alter_domainrisk_ref'),
        ('controls', '0008_alter_control_risk_masters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='risk_masters',
        ),
        migrations.AddField(
            model_name='control',
            name='risks',
            field=models.ManyToManyField(blank=True, to='risks.risk', verbose_name='Riesgos asociados'),
        ),
    ]
