# Generated by Django 4.1 on 2022-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
        ('risks', '0007_alter_risk_options_remove_risk_risk_master_and_more'),
        ('controls', '0009_remove_control_risk_masters_control_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='controls', to='risks.risk', verbose_name='Riesgos asociados'),
        ),
        migrations.AlterField(
            model_name='control',
            name='sub_processes',
            field=models.ManyToManyField(blank=True, related_name='controls', to='process.subprocess', verbose_name='SubProcesos asociados'),
        ),
    ]
