# Generated by Django 4.1 on 2022-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0010_alter_control_risks_alter_control_sub_processes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='ref',
            field=models.CharField(max_length=140, unique=True, verbose_name='REF'),
        ),
    ]
