# Generated by Django 4.1 on 2022-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_alter_control_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='is_elc',
            field=models.BooleanField(default=False, verbose_name='¿Es un control ELC?'),
        ),
    ]
