# Generated by Django 4.1 on 2022-10-25 16:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_control_is_elc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='testing_procedure',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Evidencia'),
        ),
    ]
