XXXX
XXXXXX XX XXXXXXXXXXXXXXXXXXX XXXX
XXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
XX
XXX
BBBBBBB BBBBBB

BBBB BBBB

BBBBB BBBBB gettext(u'Dashboard One') BBBBBBBB

BBBBB BBBBBBB

XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXX XXX XXXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXX XXX XXXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXX XXX XXXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB