BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXX
        XXXXXXX
      XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Riesgos que pertenecen al Sub Proceso') 
      XXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBB B B
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
      XXXXXXX
        XXXX
          XXX XXXXXXXXXXXXX XXXXXXX gettext(u'#') XXXXX
          XXXX gettext(u'DESCRIPCIÓN') XXXXX
          XXXX gettext(u'CONTROLES') XXXXX
          XXXX gettext(u'MARCOS NORMATIVOS') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXX
          XXXXFFFFXXXXXXXXX
          XXXX
            BB BBBBBBBBBBBBBBBBBBB B B
            BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXX
              FFFFFFFFFFFFFFFFFXXXXXXX XX
            BBBBBB
            BBBB
             gettext(u'Sin controles definidos para este riesgo') 
            BBBBB
          XXXXX
          XXXX
            BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
             X XXXX
            BBBBBB
          XXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBB
    XXX gettext(u'No se han creado riesgos para este Sub Proceso') XXXX
    BBBBB
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXX gettext(u'Nuevo Riesgo') XXXX
      XXXXXX
    XXXXXX
  XXXXXX

XXXXXX
