BBBB BBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX
      XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Datos del Riesgo') 
      XXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Referencia') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Descripción') X XXXXXXXXXXXFFFFXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sub Proceso') X XXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Categoría') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Impacto') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Probabilidad') X XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Rating') X XXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXX gettext(u'Editar') XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXX gettext(u'Eliminar') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
