# Generated by Django 4.1 on 2022-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='employees', to='companies.company', verbose_name='Compañías a las que pertenece'),
        ),
        migrations.AddField(
            model_name='user',
            name='companies_admin',
            field=models.ManyToManyField(blank=True, related_name='admins', to='companies.company', verbose_name='Compañías qué administra'),
        ),
    ]
