# Generated by Django 4.1 on 2022-08-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='employees', to='companies.company', verbose_name='Compañías a las que pertenece'),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Clave de recuperación de contraseña'),
        ),
    ]
