# Generated by Django 4.1 on 2022-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_companies_user_companies_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2, verbose_name='Idioma de notificaciones'),
        ),
    ]
