# Generated by Django 4.1.3 on 2023-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_notification_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, verbose_name='¿Es auditor?'),
        ),
    ]
