# Generated by Django 4.1 on 2022-08-22 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_companies_user_remember_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la creación del objeto.', verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='Fecha de modificación')),
                ('action_description', models.CharField(max_length=300, verbose_name='Descripción de la acción realizada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción de usuario',
                'verbose_name_plural': 'Acciones de usuario',
                'ordering': ['created'],
            },
        ),
    ]
