# Generated by Django 4.1.3 on 2024-12-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_alter_riskcompany_name'),
        ('users', '0004_user_is_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audit_domain_risk',
            field=models.ManyToManyField(blank=True, related_name='auditors', to='risks.domainrisk', verbose_name='Dominios de Riesgo que audita'),
        ),
    ]
