# Generated by Django 4.1 on 2022-09-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0004_actionloguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies_admin',
            field=models.ManyToManyField(blank=True, related_name='admins', to='companies.company', verbose_name='Compañías qué administra'),
        ),
    ]
