# Generated by Django 4.1 on 2022-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companydomainriskexperts_expert'),
        ('users', '0005_user_companies_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies_evaluate',
            field=models.ManyToManyField(blank=True, related_name='evaluators', to='companies.company', verbose_name='Compañías que evalúa'),
        ),
    ]
