# Generated by Django 4.1 on 2022-10-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_companies_evaluate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companies_evaluate',
        ),
    ]
