# Generated by Django 4.1 on 2022-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_companies_evaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Cargo que ocupa'),
        ),
    ]
