BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXFFFFXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Eliminar') XXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
    XXXXXX
  XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBB