BB BBBBBBBBBBB
  BBB BBBBB BB BBBB
    BBB BBBBB BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX FFFFFFXXXXXX
    XXXXXX
    BBBBBB
  BBBBBB

  BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
  XXXXXX
  BBBBBB
BBBBB