#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# N.B. If only .env files supported variable expansion...
#export CELERY_BROKER_URL="${REDIS_URL}"

if [ -z "${KRM_POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${KRM_POSTGRES_USER}:${KRM_POSTGRES_PASSWORD}@${KRM_POSTGRES_HOST}:${KRM_POSTGRES_PORT}/${KRM_POSTGRES_DB}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${KRM_POSTGRES_DB}",
        user="${KRM_POSTGRES_USER}",
        password="${KRM_POSTGRES_PASSWORD}",
        host="${KRM_POSTGRES_HOST}",
        port="${KRM_POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Esperando for PostgreSQL to become available...'
  >&2 echo "POSTGRES_HOST: ${KRM_POSTGRES_HOST}"
  sleep 1
done
# >&2 echo 'PostgreSQL is available'

exec "$@"
