BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
    BB BBBBBBBBBBBBB BB BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
      XXX
    BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
      XXX
    BBBBB
  XXX
XXXXXXXXX
XXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
  XX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
  XX       XX XXX XXX XXXXXXXX XXXXX
  XX       XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX       XXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX       XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

  XX       XX XXXXXXXXXXXXXX XX XX XX XXXXXXXXXX XX XXXX X
  XX         XXXXXXXXXXXXXXXXXXXXXXX
  XX         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX       X
  XX   XXX
  XX XXX
XXXXXXXXX

BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Respuesta incompleta') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Quedan campos pendientes de completar. Por favor, revise su respuesta') 
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
         gettext(u'Debe establecerse un plan de remediación, en la parte inferior podrá rellenarlo si es el Control Owner') 
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX

  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'RESPUESTAS') XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX XXXXX X XXXXXXXXXX XXXXXXX gettext(u'RESULTADO ACTUAL:&emsp;') XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B
      BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBBBB
      BBBBBB
    BBBB
      XX XXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Todavía no hay respuestas para este test de control') 
      XXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXX XXXXXXXXXXXXX gettext(u'PLANES DE REMEDIACIÓN') XXXXX
      BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBB
      BBBBBB
    BBBBB
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBB BB BBBB BB BBBBBBBBBBBBBBBBBBB BB BBBB
    BB BBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'NUEVA RESPUESTA') XXXXXX
          XXXXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX gettext(u'Supervisión del control') XXXXXXXXX
                  XXXXXXXXXXX gettext(u'Si necesita más información para poder marcar el control como Completado, marque la siguiente casilla. Esto le devolverá el control al responsable de cumplimentarlo para que pueda aportar más información. Utilice el campo de texto anterior para requerir la información necesaria.') XXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  BB BBBBB BB BBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX
                      FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  BBBBB
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX
                  XXXXXXXX gettext(u'Comentario') XXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Revisión completada') XXXXXXXXX
            XXXXXXX
            XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
          XXXXXX
        XXXXXXX
      XXXXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'NUEVO PLAN DE REMEDIACIÓN') XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXXXXX XXXXXXXXXXXXX gettext(u'Datos del plan de remediación') XXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXX XXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXX XXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXXXXXXXX
                    XXXXXXXX gettext(u'Descripción del Plan de Remediación') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
              XXXXXXX
              XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
            XXXXXX
          XXXXXXX
        BBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'NUEVA RESPUESTA') XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX

              XXXX XXXXXXXXXX XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXX XXXXXXXXXXX XXXXXXX
                    XXXXXXXX gettext(u'Resultado y evidencias') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  BB BBBBB BB BBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX
                      FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  BBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                BB BBBBB BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       gettext(u'Por favor, recuerde indicar la ruta de WorkSpace en la que se almacena la documentación que evidencia la ejecución del control') 
                    XXXXXX
                BBBBB

                  XXXXXXXXXX
                    XXXXXXXX gettext(u'Comentario') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Testeo finalizado') XXXXXXXXX
            XXXXXX

          XXXXXXX
        BBBBB
      XXXXXX
    BBBBB
BBBBB
XXXXXXXXXXXXXXXXXXXXX

BBBBBBBB BBBBBBB
