BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XX XXXXXXXXXXXXX
    XX   XXXXXXXX
    XX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX     X
    XX       XXXXXXXXX X
    XX         XX XXX XX XXXX XX XXXXXXXX
    XX         XXX XXXXX

    XX         XX XXX XXX XXXXXXX XXXX XX XXXXXX XX XXXXXXX
    XX         XXXXXXXX XXXX
    XX       X
    XX     X
    XX   X
    XX   XXXXXXXXXXXX XX X
    XX     XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX     XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX   XX
    XX   XXXXXXXXXXXX XX X
    XX   XXX

    BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
    BB BBBBBBBBBBBBB BB BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
      XXX
    BBBB
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
      XXX
    BBBBB

  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B
  XXXX XXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
         gettext(u'Debe establecerse un plan de remediación, en la parte inferior podrá rellenarlo si es el Control Owner') 
      XXXXXX
    XXXXXX
  XXXXXX
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
XXXX XXXXXXXXXX XXXX XXXXXX
  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
       gettext(u'Puede editar el plan de remediación ya adjunto, en la parte inferior podrá rellenarlo si es el Control Owner') 
    XXXXXX
  XXXXXX
XXXXXX
BBBBB

XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Datos del Test de Control') X XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'RESPUESTAS') XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX XXXXX X XXXXXXXXXX XXXXXXX gettext(u'RESULTADO ACTUAL:&emsp;') XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B
      BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBBBB
      BBBBBB
    BBBB
      XX XXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Todavía no hay respuestas para este test de control') 
      XXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXX XXXXXXXXXXXXX gettext(u'PLAN DE REMEDIACIÓN') XXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBB BB BBBB BB BBBBBBBBBBBBBBBBBBB BB BBBB
    BB BBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'NUEVA RESPUESTA') XXXXXX
          XXXXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX gettext(u'Supervisión del control') XXXXXXXXX
                  XXXXXXXXXXX gettext(u'Si necesita más información para poder marcar el control como Completado, marque la siguiente casilla. Esto le devolverá el control al responsable de cumplimentarlo para que pueda aportar más información. Utilice el campo de texto anterior para requerir la información necesaria.') XXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  BB BBBBB BB BBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX
                      FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  BBBBB
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX
                  XXXXXXXX gettext(u'Descripción') XXXXXXXXX
                  FFFFFFFFFFFFFFF
                  XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Revisión completada') XXXXXXXXX
            XXXXXXX
            XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
          XXXXXX
        XXXXXXX
      XXXXXX
    BBBBB


    BB BBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'NUEVO PLAN DE REMEDIACIÓN') XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXX XXXXXXXXXXX XXXXXXX
                    XXXXXXXX gettext(u'Datos del plan de remediación') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                      FFFFFFFFFFFFFFF
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXXXXXXXX
                    XXXXXXXX gettext(u'Descripción') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
              XXXXXXX
              XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
            XXXXXX
          XXXXXXX
        BBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'NUEVA RESPUESTA') XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXX XXXXXXXXXXX XXXXXXX
                    XXXXXXXX gettext(u'Resultado y evidencias') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  BB BBBBB BB BBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX
                      FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                  BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                  XXXXXXXXXX
                    XXXXXXXX gettext(u'Descripción') XXXXXXXXX
                    FFFFFFFFFFFFFFF
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
              XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Testeo finalizado') XXXXXXXXX
              XXXX XXXXXXX
              XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX XXX
            XXXXXX

          XXXXXXX
        BBBBB
      XXXXXX
    BBBBB
BBBBB

BBBBBBBB BBBBBBB
