BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXXX
    XXX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Datos del Control Test') XXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
  XXXXXXXXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB

      
      XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX  XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX  XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX  XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXXXXXXXXXXXX
    
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Guardar') XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX
          XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
      XXXXXX
    XXXXXXX

XXXXXX
XXXXXXXXXXXXXXXXXXXXX


BBBBBBBB BBBBBBB