BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXX
      XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
          XXXXXXXXX X
            XX XXX XX XXXX XX XXXXXXXX
            XXX XXXXX

            XX XXX XXX XXXXXXX XXXX XX XXXXXX XX XXXXXXX
            XXXXXXXX XXXX
          X
        X
      X
      XXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXXX XX X
      XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXX
          XXXXXXXXXXX XXXXXXXX
    XXX
  XXX
XXXXXXXXX
XXXXXXXX
  XX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXXXXXX X XXXXXXXX XXXXXXX X
  XX   XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX   XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX   XX XXX XX XXXX
  XX     XXXXXXXXXX XXXXXXXXXXXX
  XX     XXXXXXXXXXXXXXXXXXXXXXX
  XX   X
  XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
        XX XXX XXX XXXXXXXX XXXXX
        XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XX XXXXXXXXXXXXXX XX XX XX XXXXXXXXXX XX XXXX X
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

    XXX
XXX
XXXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Respuesta incompleta') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Quedan campos pendientes de completar. Por favor, revise su respuesta') 
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
         gettext(u'Debe establecerse un plan de remediación, en la parte inferior podrá rellenarlo si es el Control Owner') 
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

XXXX XXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXXXXXXXXXXX XXXXXXX
XXXXXX


XXXX XXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'RESPUESTAS') XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX XXXXX X XXXXXXXXXX XXXXXXX gettext(u'RESULTADO ACTUAL:&emsp;') XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B
      BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBBBB
      BBBBBB
    BBBB
      XX XXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Todavía no hay respuestas para este test de control') 
      XXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXX XXXXXXXXXXXXX gettext(u'PLANES DE REMEDIACIÓN') XXXXX
      BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBB
      BBBBBB
    BBBBB
  XXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBB BB BBBB
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Administración del Control') XXXXXX
      XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
            XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXX
            BB BBBBB BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
            BBBBB
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Finalizar revisión del control') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
BBBBB

BBBBBBBB BBBBBBB
