<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>es.eci.fdos</groupId>
		<artifactId>eci-pom</artifactId>
		<version>1.0.0</version>
	</parent>

	<groupId>es.eci.ocp.helm</groupId>
	<artifactId>poc-helloworld-deployment</artifactId>
	<packaging>pom</packaging>
	<version>1.0.0-SNAPSHOT</version>
	<name>krm-kpmg</name>
	<description>Configuracion Despliegue del componente</description>

	<build>
    <plugins>
      <!-- Formamos un zip con las plantillas y los ficheros de configuracion -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <descriptors>
                <descriptor>assembly/configuration.xml</descriptor>
              </descriptors>
              <finalName>${pom.artifactId}-${pom.version}</finalName>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>ant-deploy</id>
                        <phase>deploy</phase>
                        <configuration>
                            <target>
                                <echo>V. de proyecto vista por ant: ${project.version}</echo>
                                <condition else="http://nexus.elcorteingles.int/content/repositories/fichas_dcos-releases/" property="url" value="http://nexus.elcorteingles.int/content/repositories/fichas_dcos-snapshots/">
                                    <contains string="${project.version}" substring="-SNAPSHOT"/>
                                </condition>
                                <condition else="fichas_dcos-releases" property="repository" value="fichas_dcos-snapshots">
                                    <contains string="${project.version}" substring="-SNAPSHOT"/>
                                </condition>
                                <exec dir="${basedir}" executable="/bin/sh" osfamily="unix">
                                    <arg value="${MAVEN_HOME}/bin/mvn org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy-file -DgroupId=${project.groupId} -DartifactId=${project.artifactId} -Dversion=${project.version} -U -Dfile=${basedir}/target/${project.artifactId}-${project.version}.zip -Durl=${url} -DrepositoryId=${repository}"/>
                                    <env key="DEPLOYMENT_USER" value="${DEPLOYMENT_USER}"/>
                                    <env key="DEPLOYMENT_PWD" value="${DEPLOYMENT_PWD}"/>
                                </exec>
                                <exec dir="${basedir}" executable="cmd.exe" osfamily="windows">
                                    <arg value="/C"/>
                                    <arg value="${MAVEN_HOME}/bin/mvn"/>
                                    <arg value="org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy-file"/>
                                    <arg value="-DgroupId=${project.groupId}"/>
                                    <arg value="-DartifactId=${project.artifactId}"/>
                                    <arg value="-Dversion=${project.version}"/>
                                    <arg value="-U"/>
                                    <arg value="-Dfile=${basedir}/target/${project.artifactId}-${project.version}.zip"/>
                                    <arg value="-Durl=${url}"/>
                                    <arg value="-DrepositoryId=${repository}"/>
                                </exec>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.8.2</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
    </plugins>
  </build>

</project>
