BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha de vencimiento del plan de remediación') X XXXXXXX 
      XXXX
      XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Usuario') X XXXXXXX 
      XXXX
      XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fichero adjunto') X XXXXXXX
      BB BBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXX  gettext(u'Descargar adjunto') XXXX

      BBBB
         gettext(u'No se ha adjuntado ningún fichero') 
      BBBBBXXXX
      XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Descripción') X XXXXXXX XXXX
      FFFF
    XXXXXX
  XXXXXX
XXXXXX
