BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Usuario') XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Comentario') XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXFFFFXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Estado propuesto') XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fecha') XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Evidencia') XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXX gettext(u'Adjunto') XXXX
            BBBB
               gettext(u'Sin evidencia') 
            BBBBB
          XXXXXX
        XXXXXX
        XXXX XXXXXXXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
