BBBBBBB BBBBB BBBBBBBB BB BBBBB
BBBBBBB BBBBBBB BBBBBBB BBBBBBBB BB BBBBBBB

XXXXXXXXXXXXXXXXXXXX XXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    
XXXXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXX

XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXXXX