BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XXXX X  gettext(u'Test de Control') BBBBBBBB

BBBBB BBBBBBBB

BBBBBBBB

BBBBB BBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Controles') XXXX
    XXXXXX
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
        
    BBBBBBB
BBBBBBBB BBBBBBBBBBBB
