BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XXXX X  gettext(u'Test de Control') BBBBBBBB

BBBBB BBBBBBBB

BBBBBBBB

BBBBB BBBBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Test de Control: ')  
    XXXXXX
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB

  XXXX XXXXXXXXXXXX

     #
 #
 #


    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXX
            XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Datos del Test de Control') X 
            XXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'RESPUESTAS') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB B B
              BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBB BBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
              BBBBBB
            BBBB
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Todavía no hay respuestas para este test de control') 
            XXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B

            XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Plan de Remediación') XXXXXX
              XXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBB
                BBBBBB
              BBBBB
            XXXXXX
            XXXXXX
            XXXXXX


            BB BBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBB
              XXXX gettext(u'NUEVA RESPUESTA') XXXXX

              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
                  FFFFFFFFFFFFFFF
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXX gettext(u'Fichero adjunto de evidencias del control') XXXXXXXX
                    XXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                      
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX gettext(u'Selecciona un fichero') XXXXXXXX
                    XXXXXX
                  XXXXXX

                  FFFFFFFFFFFFFFF

                  XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX  XXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX gettext(u'Testeo finalizado') XXXXXXXXX
                      XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
              XXXXXXX

            BBBBB
          XXXXXX

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX

BBBBBBBB
