BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XXXX X  gettext(u'Test de Control') BBBBBBBB

BBBBB BBBBBBBB

BBBBBBBB

BBBBB BBBBBBB

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
    XXX
  XXX

XXXXXXXXX

BBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Tests de Proceso') XXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Test de Proceso: ')  XXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Test de Control: ')  
  XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXX

   #
 #
 #


  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXX
          XXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Datos del Test de Control') X 
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX gettext(u'RESPUESTAS') XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B
          BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BB BBB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BBBBBB
          BBBB
          XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Todavía no hay respuestas para este test de control') 
          XXXX
          BBBBB

          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
          XXXX gettext(u'PLAN DE REMEDIACIÓN') XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB

          BB BBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB BB BBBB

          XXXX gettext(u'NUEVA RESPUESTA') XXXXX

          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
              FFFFFFFFFFFFFFF
              XXX
                XXXXXXXX gettext(u'Si necesita más información para poder marcar el control como Completado, marque la siguiente casilla. Esto le devolverá el control al responsable de cumplimentarlo para que pueda aportar más información. Utilice el campo de texto anterior para requerir la información necesaria.') XXXXXXXXX
              XXXX
              FFFFFFFFFFFFFFF
              XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
                BB BBBBB BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                BBBBB
              XXXXXX
              XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Es necesario especificar la información que necesita utilizando caja de texto de arriba') 
              XXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX  XXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX gettext(u'Revisión completada') XXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXXX
          BBBBB
        XXXXXX

      XXXXXX
    XXXXXX
  XXXXXX

XXXXXX

BBBBBBBB
