BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XXXX X  gettext(u'Test de Control') BBBBBBBB

BBBBB BBBBBBBB

BBBBBBBB

BBBBB BBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Test de Control: ')  
  XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXX

   #
 #
 #


  XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXX
          XXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Datos del Test de Control') X 
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX

        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX gettext(u'RESPUESTAS') XXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX gettext(u'RESULTADO') XXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBB BBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB B B
            BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BB BBB BBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB
            BBBBBB
          BBBB
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Todavía no hay respuestas para este test de control') 
            XXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
            XXXX gettext(u'PLAN DE REMEDIACIÓN') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB

          BB BBBBBBBBBBBBBBBBBBB BB BBBB BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB BB BBBB
          XXXX gettext(u'NUEVA RESPUESTA') XXXXX

          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
              FFFFFFFFFFFFFFF
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Fichero adjunto de evidencias del control máximo(50MB)') XXXXXXXX
                XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                  
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXXXXXXX gettext(u'Selecciona un fichero') XXXXXXXX
                XXXXXX
              XXXXXX

              FFFFFFFFFFFFFFF

              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX  XXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX gettext(u'Testeo finalizado') XXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cancelar') XXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXXX

          BBBBB
        XXXXXX

      XXXXXX
    XXXXXX
  XXXXXX

XXXXXX

BBBBBBBB
