BBBB BBBB
 gettext(u'Sin asignar') 

BB BBBBBBBBB B B

XXXXXXX
  XXXXXX X
    XXXXXX XXXXX XXXXXXXXXXX
    XXXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXX XX
    XXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X
XXXXXXXX

XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXXXXXXX
      XXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'REF') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Sociedad') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Descripción') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Evidencia') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Dominios de Riesgo') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Número de riesgos') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Control Owner/Supervisor') XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Efectividad') XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BB BB BBB
    XXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX
          XX XXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBBB
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBXX
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBXXXXXXXXX
        XXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBBB
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXX
        BBBB
         gettext(u'Sin asignar') 
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXX
          XXXXXXXXXXXXXXXXXX XXXXXXX
        BBBB
         gettext(u'Sin asignar') 
        BBBBB
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBB BBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        BBBBB
      XXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX

BBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
   gettext(u'Sin controles') 
XXXXXX

BBBBB
