BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'FECHA') X XXXXXXX XXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'USUARIO') X XXXXXXX XXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'FICHERO ADJUNTO') X XXXXXXX
      BB BBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXX  gettext(u'Descargar adjunto') XXXX

      BBBB
         gettext(u'No se ha adjuntado ningún fichero') 
      BBBBBXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'DESCRIPCIÓN') X XXXXXXX XXXX
      FFFF
    XXXXXX
  XXXXXX
XXXXXX
